#+title: Communication

* Communication is fake, actually
----
Surely you've noticed it by now. People know and use different definitions of relatively common words in English. I don't know how it is outside of English, I'm not there. All I know is, this approaches absurdity.

Now, the evolution of language is a known thing. A thing so widely known as to be tiresome. And, as an extension of this, we have on the inner layer of culture slang, and on the outer layer loan-words.

But now in the age of the Internet, slang moves faster than ever. In fact, I would go so far as to say that its current trajectory can be likened to a snowball rolling down a mountain: innocuous, but inexorably accelerating till it hits the ground.

What's the ground? Babel. Total loss of mutual intellegibility. The older generations will maintain a fairly well-rooted dialect while their children and grandchildren sail far and away with a much smaller and more nuanced vocabulary.

----

This is not the problem I came here to talk about. It's just a fun look ahead (or in the mirror?) that lies tangent to the real issue:

_Every single person_ speaks a different language.

Here's some arguments, for those who are into it.

1. The logical argument from thought:
  - All humans over the course of their development arrive at a unique cycle of thought
  - All verbal/linguistic expression is derived directly from thought
  - Thus, all verbal/linguistic expression is the product of a unique cycle of thought.

that, my friend, is either a perfect syllogism or a cheap definitional cop-out. If your language distinguishes between those. Mine does but only when it's applied to something I disagree with.

2. 
  - All misunderstandings are caused by different points of view
  - Different points of view are...
  - Ack screw it this is just drawing an obvious conclusion that was foregone from the first line. sorry to waste your time.
