baseURL = "https://mitchmarq42.xyz/"
languageCode = "en-us"
title = "The Best Site Ever! (not)"

theme = ["hugo-redirect", "lugo"]
# theme = "after-dark"

[markup]
  [markup.highlight]
  style = "fruity"