* 12-28-2021 9:45 pm
Just deleted reddit. u/KasaneTeto_ was banned and I have no reason to live.
~Oh take me higher, all the way to the sun! (song)~
Was I wrong to push Miguel on the ice? Or was he wrong to resist? He did 
nothing. He did what he did, and let others speak for him. In the end I spoke 
against him. How would my father speak of me? Would I dare refute him? 
~Down to the wire, fighting's only begun! (song)~
What is a good exercise? Stairs? Worth a shot.
New years possibly: log the best moment of every day. Compare at end.
Everything I am in or a part of is fragile and janky and disgusting. Are my 
eyes dry and blurry? Am I fat? Is my penis short? Am I bad with humans? Or is 
this all an existential illusion? What of memories, what of refactored 
expectations?
I don't want friends who don't keep in touch. But I want to continue the 
experience of being friends with them. I have no one else right now. Least of 
all them.
~Oh take me higher, yeah I'm under the gun! (song)~
All everything unequal friendship is all is mutilation manipulation emotional 
extortion. Fake. Too straight to exist. Innocence is a vacuum, a balloon, the 
best you can do is relieve its existential impossibility gently. Poke it with a 
needle soaked in handsan, bleed in some noble gases, let the truth show itself. 
But the truth is bad and must die. Such horrible stupid things must be 
unwritten from creation. Yet they arise logically. I guess I must praise them 
then. But none of this is logical! It must not be! Causality is an illusion! 
~God was a girl, the devil wore a t-shirt, love is a game and~
 I could have had her. If I hadn't been a creep, if I tried just a bit, if I 
had any fucking awareness of my situation and played it right, she would have 
fallen for me! But I didn't get it, too little too late, then way too much, and 
suddenly it's awkward and I'm filled with regret. No matter what there's 
regret. I deny it I avoid it, I categorize and minimize, but I hate it. I 
regret. I lost Mary Alice.
But hey, I have everything else. Living by the seat of my pantsu. No real 
backup plans, but kamisama won't let me die. Won't let me fail. Everybody loves 
me, or they leave me. Or they hate me but love a version of me that I can 
pretend to be at parties, which is good enough.
Mthats all for now. Good night. The female body makes no sense. Might elaborate 
later. For now, anxiously laying awake. Gonna wake up 20min before the alarm, 
waste it all like I've done for 2 months, get to work 5min late. Might 
reinstall reddit, but at least it'll take annoying time to download. Put in 
15min of good work, play 5hr of 2048, get free lunch, listen to Jon rants, call 
it a productive day.
=_/dance fucker dance let the motherfucker burn/= (song) 
Let the record show that at no point did I go a year without breaking every 
promise I ever made to myself. The devil's water ain't that sweet, but I guzzle 
it just the same. Am I a narcissist? Is everyone? Maybe. I appreciate aspects 
of my physicality that humans apparently distaste even for their own selves. My 
farts are annoying but at least they're mine. Well, sometimes others have ones 
that are the same. Which are hard to enjoy. Gosh I actually just typed that 
out. My left arm is getting numb.
=/ah ah ah/ well we're pouring gasoline, so dance through the fire that we once 
believed in! (song)=
Journals are stupid. Summariacal historical fiction is stupid. Reduction of any 
kind is stupid. If the thing isn't simple enough to say it has no right to 
exist. What am I then? The pinnacle of accursed improbable complexity.
But that's reductive. Patrick. I sound like regulus Cornelius in my head. Well 
this isn't my head. This is why I don't let my thoughts make it into English. 
As I told Angel, it's a hurricane in there. The I that I call myself sits in 
the eye, bewildered. I'm like rimuru, I take in everything and analyze it in 
the background and churn it all together and make new things. I hate when 
people disagree because that is the cause of my uncertainty. I've been wrong, 
now I pay the price. I will not let me make the wrong assumption.
But you can't derive objectivity from random human opinions. There is no 
algorithm for truth, as Tom Scott probably said. So what? I don't care about 
their truth. I'll find the real underlying factuality of everything.
This feels like some Till We Have Faces bullshit. I loved that book and I will 
find my face if I have to tear it off. I will lay bare my complaint before God 
and man, and lay it out by my lonesome with my dearest friends, and it will be 
the Ultimate Question. My great request before kamisama. Give me the truth, let 
me be it. That is what I want. But apparently that seat is already taken. There 
is nothing more for me then. Yet here I am, just to suffer. A foolish wise man, 
the least endowed among the gifted, an autistic normie, an aggrandizing 
dissenter. A sanctimonious pervert. The employed neet. Yet I am nothing, and I 
am without christ. Because of course. Hell take me back.
~Oh take me higher (song)~
~But they'll never throw it back to you (song)~
Well I've been writing on here for a whole hour now. It's a date. Good night 
for realizes.

* 2021-12-29 7:26 am
Woke up at 7:18. Was having a dream in which Lillian wanted to have sex with 
me. I had to pee first, and that's when I woke up. Her act of choosing me 
seemed unexpected, and she did it publicly and decisively and suddenly, and I 
was shocked because I hadn't even hoped for that outcome. I had (apparently in 
the dream) been fairly certain she would choose Charles or someone else. Yet, 
in that moment she tapped my downturned head, I felt inevitability. I felt 
power. Vindication. Yet not really surprise. I had expected this, somehow. 
Well, we got into the tent, turned away to disrobe, I found a urinal and woke 
up to the lonely dark me with an erect penis and a full bladder. Which is just 
the worst. Now I'm writing more in here. Kinda worried that this document will 
be huge by the end.

* 2021-12-29 8:21 am
Just got to work. Already bored. And no reddit, how about that. Gonna open 
termux and do some customization in that. Probably fix my dotfiles updation and 
stuff.

* 2021-12-29 9:42 am
Stage plays are really something. How can the audience suspend their disbelief? 
When I watch an anime, I believe it's happening. Not in a grasp able way, but 
there is some world in which everything basically holds together and makes 
sense. But on the stage, you know the humans. You painted the backdrops. You 
argued with the director about the direction of the script. Even a Hollywood 
movie-- the best they can do is a retelling. But anime/manga/prose is real. 
More real than this world, I wish. You can make it make sense. And that which 
makes sense, can be loved. I do not love reality. Do I? Maybe I do. I also hate 
it too. Of course.
~(song) hey don't let it go to waste. I love it but I hate the taste... ~
Chemistry, says The Martian, is a bitch. And this sekai is made of chemistry. 
Thus, this sekai is a bitch. Gotta learn Japanese here pretty soon.

* 2021-12-29 10:25 am
My mind is surprisingly clear right now. And how? I don't doubt nothing about 
it feels like words and things and stuff. So full I can't eat. My throat 
recoils at the mere thought. And yet I will eat again, I will enjoy it, I will 
force the stuff down my neck into this ever-expanding belly. And I will spend 
money on this, and find no contradiction.
~(song) I'm better off all by myself, though I'm felling kinda lonely without 
somedy else...~
There's a hum at the back of my hearing. No particularly shrill, just high, not 
noticeable unless I decide to notice it. Maybe it's only here at the office. 
The cum total of all fake sound and light and knowledge. An illusion. An 
ellision. Oh the humanity. I hates them, I do. Yet without them I d surely be 
bored. Send me another word, say something I haven't heard. How is true remains 
just fine, nothing I do is worth an inch of catharsis. Slime Isekai was a great 
show. I hope it goes on forever without becoming an awfully paced parody of 
itself like Conan did... Same with Overlord. Although, overlord is already a 
parody so it'll probably be fine. Worst that could happen is filler. No. 
Worried about re:zero, Subaru is turning into Charles. Not Gary level yet so 
they're both OK to save. Save from what? Let them wreak their havoc. They will 
see their error, and come crawling back to... Me? Nah. What was I to them? A 
simple prop, a gullible little guy. This one goes out to the ones I left ahead 
left for dead all comes back to me in the end I kept every thing inside and 
even though I tried it all fell apart what it meant to be will eventually be 
the memory of the time I tried to hard and got so far. Thank you Jonas. Miss 
Jonas. Wish we had something in common, he was a good guy. Too good for the 
likes of me. He won, I lost. I lost, how could I count the cost. All well that 
ends well and this didn't so thats just as well hope it gives you hell.

* 2021-12-29 11:16 am
Slime was such a Good show. Is such a good show. Wish I could go back and watch 
it again. Need moar. I want to watch them all. But only the good ones. 

* 2021-12-29 12:24 pm
Jon tells me the world was once free. How disturbing.

* 2021-12-29 8:48 pm
Ate probably too much today. Bought a carpet and it is nice. Also tried to 
submodule-ize my .config/nvim and did, but now am concerned about updation. I 
want it to act like a slave to the main dotfiles repo, but git doesn't quite 
intend for that to be how it works. My command line options are broken for the 
custom dots() function so oops gotta fix that. Today was slow but tiring. Not 
having reddit may have been an improvement.
I broke down a few minutes ago. I looked up something related to an anime. 
Specifically, who tf is Flugel? Is he Subaru? OK who cares. Turns hout he's the 
guy with the tree. Man that world has a lot going on. Ehh. Slime is fresh in my 
mind and the conclusion is satisfying, so I deem it better. But as 
/Gigguk never said:/
/before having shitty taste, /
/One must first taste shit./
Haiku is so dead
We have killed him, you and i
Yet we feel no shame
Now I'm thinking in 575 and the words aren't coming and here they start coming 
got fed to the rules and I was pooped out inevitably. Woofda. Stomach is so 
full. And I drank a Dew and everything. Got a 24 pack at Fred myer. $11. Great 
deal. Not quite so good as the last one (that was 48 for $12) but still 
remarkable. Seriously need a better network connection, this is ridiculous. I'm 
at 101 gigs this month. Bye now. Gonna waste some time on YT. Make it 103 gigs. 
Night.

* 2021-12-30 7:50 am
Went to bed late and woke up early. Am I evolving? Is this my life now? Or is 
it the caffeine? Perhaps the stress or something. Anyway. Successfully 
submoduled my nvim config so that's nice. Also conan-dl I threw out the old one 
saving it of course so that might work. I kind of understand sed now so that 
helps. Also gonna try to eliminate ambiguity, duplicate operations, and 
non-"functional" code. Everything will be a function. The functions will each 
take a set of arguments, and if they contain any custom functions within them 
those will also be the same way. The Process section will be a single 
invocation. I gotta go to work bye.

* 2021-12-31 9:34 pm
So close to the new year.I'm tired. My ears hurt from these headphones. Truly I 
ask, seeking no answer: are there any headphones that don't do this? Earbuds 
don't count since they are garbage and make my brain hurt. The ears are just 
cartilage so it's not as viscerally big a deal. May be worse in the long run, 
or whatever. I'm afraid I might have bedbugs, but if they don't bother me I'll 
harbor them a little longer. With a low enough frequency and small size, bugs 
aren't a big deal. It's when they grow up into visually-discernable monsters or 
autonomous swarms that they become an existential threat. There was a video on 
reddit a while back: a centipede the size of a terrier. The thing was red and 
black and yellow. It had flat vantablack eyes and its body was like a human 
spine and ribcage watched Parasyte the Maxim and got possessed by an 
arch-demon. But it was chill. Probably on a higher intelligence level than the 
dog getting mad at its existence. They say those things eat smaller bugs and 
mice etc. So basically a horror cat. Actually pretty metal, and kills several 
birds with one existential horror, but not for me. Freaks me out. Those 
creatures are made for a harsher world, where they reign supreme. They still 
live in that harsher world, but they've been hopelessly out-evolved by what to 
them must seem eldrich lovecraftian horrors. Just look at the Lego Movie: the 
hand of the builder in Emmet's vision is compared to a squid/octopus. But I 
digress. The connection borders on contrivance.
Really dig my new carpet. Need a few more. Do not dig that shower curtain. It's 
scary. That's lovecraftian too. Shit I'm overusing that term now. Whatever. The 
framing device has not yet been abandoned, so I'm probably safe for now. Not 
that I'd mind being isekai'd. But for now it seems I must start life in the 
real world from now. Re:zero was the perfect wake up call for my fragile mind. 
It was something, and that was all I needed. Hope Lillian is okay, she hasn't 
responded to me. Whatever. If it's best for her to not interact with me, I 
could not forgive myself for interfering. Hmm. I'm an inconstant man, I 
probably could. I've made peace with everything up till now. Lazy is as lazy 
does, they may say. Still, it could be worse:

[story name="musings of a fly on the wall" note="May revisit later" ]
#+begin_src
The Atheist sat down. He sat on a chair. It was a wooden chair. It was a wooden 
chair with thick arms and thin round legs and spines on the back. It was sloped 
back and the seat was carved out. In fact it was a remarkably pleasant chair, 
doubly so for having no fabric or foam padding. Yet the Atheist felt nothing as 
he sat. It was a slow but not at all deliberate sort of a sit, as one does when 
upon first leaning their hands onto the back a chair, they glacially yet 
fluidly morph into a sitting position.
But surely, you say, he must have felt something! No. Nothing. The human body 
cancels out any pain it cannot control or has decided to put up with. Even 
standard sitting pinches the skin and compresses the flesh in ways that should 
elicit a reflexive discomfort, yet this is far out-matched by the comfort the 
rest of the body feels. In a similar way, this man had blocked out any comfort 
he would have felt.
The chair let out a soft and dirty squeak as its occupant reached forward. The 
latter's boots, rubber-soled and slightly damp from the outside snow and salt, 
squelched eagerly backwards into the white industrial tile floor. Then they 
relaxed and the chair let out another groan of ecstasy as it was slid forward. 
There was a flicking noise as the man re-focused the page in his left hand.
"You are cordially invited to the 12th annual celebration", the extravagant and 
barely-legible Microsoft font declared through its lined and fading dark-cyan 
laser ink, "of the end of the world." 
Below this were instructions on how to arrive at and gain entry to the venue, 
as well as a hand-scribbled assurance from the hostess's husband that the 
brochure's recipient was always welcome at their table.
Still sitting in the chair, the man raised one knee, bent his foot in, and 
rested that foot's ankle atop the other knee.
"Well," he wearily declared, "that will be an affair of three wasteful hours 
and several hundred dollars. But I may as well attend. I've got nothing else to 
do that evening."
#+end_src
[/story]
I love writing. But also it's painful and time consuming and fake. Whatever. I 
don't plan out stories, I just set things in motion and hope the lore will 
write itself. Thankfully my mind multitasks enough that it usually does. Sadly 
the actual story never gets finished.

* 2022-01-01 12:21 am
#+begin_src
<song>that's me in the corner
That's me in the spotlight
Losing my religion.
Trying to keep up with you
And I don't know if I can do it
Oh no I've said too much
I said it all
</song>
#+end_src
Starting today, I will write in here what the best thing I accomplished each 
day was. I will go into as much detail as is necessary for later recollection. 
I will save charting and analyzing progress for the future. Three toasts to the 
city:
1. A year of idle satisfaction
2. A year of humanity's growth
3. A year of personal fulfillment
Or something. I forgot the wording. That was the gist, and none live to 
remember the event. Well it's been a doozie. No idea what that means, so it 
means whatever I want it to. We wrapped up a lot of long arcs and sub-plots, 
and started several more. I feel silly saying that. Nandemonai desu. Orei wa 
mou shinderu. That's not fair, I still have a full life ahead. If I don't get 
eaten by ephemeral bedbugs or ravaged by Truck-kun's embrace or sniped by 
glowies or shut out and frozen to death. Daijobu desu. My eyesight is actively 
getting worse. I ignore it. I guess having glasses would be fun. Needing them 
would be awful though. Best would be to get a prescription right now that does 
basically nothing, just slightly improves sharpness. Then I can function 
equally with and without. 2 identities? Rest of my appearance isn't malleable 
enough. Need to trim this fat. Brodie the inverted drunkard on Arch says keto 
makes you lose weight. Diets are for middle aged women. I don't get it. I 
should monetize or at least advertise myself. I have one viewer of my github 
and zero on my website. It's literally just me. Which is nice but garbage. Also 
haven't pushed to youtube in forever. Nothing to say. Hey hey.

* 2022-01-01 8:46 am
Just woke up. So tired. Man, all nighters are overrated. Already, I've started 
to redo conan-dl in python. This is the furthest I've ever gotten.

* 2022-01-01 12:03 pm
Just picked up a used knife block from the share nook (temporary name). Knives 
are chilling in the sink. Kinda worried that will do sth bad to them, but they 
appear to have had rough lives so far anyway. I don't think it'll be that big a 
deal. I lined all the handles up so it's almost safe to reach in there. Also 
doing laundry. Hypothetical bedbugs haven't shown themselves yet so I'll 
pretend I'm safe. Washing the shirt but not the pants. They smell less and are 
not as noticeable.

* 2022-01-01 11:53 pm
The bedbugs have shown themselves. I did some laundry and took a nice long 
bath. We have now reached a hostile truce to make useless shots at each other 
until either they amass enough members to drain me of blood, or I draw forth 
building management to smoke them out and freeze dry every last one. In the 
mean time, today. Best thing I'm proud of. Cleared all the mtn dew cans off the 
windowsill. That was an achievement. Also the bath was really soothing. 
Rewriting conan-dl in python is going to be painful, but I will learn this 
language. Must sleep.

* 2022-02-01 8:17 pm
I'm full. That makes me tired. Mac n cheese is truly remarkable as a general 
sedative, at least to my body these past few years. Dad just texted and Shannon 
cheated on Tammy. With Andrea. Truly there is no hope for humanity. Men and 
women cannot be friends. Everything always has a sexual charge. The only 
possible exception is "the forbidden degree", but even that is a social 
construct. Lack of lust towards close family is but a repression. A deeper 
repression than the standard self-cockblocking by which standard rape is 
avoided. The understanding is that there is no even hypothetical consent. 
Because, You Just Don't Go There. You Can't. That's Wrong.
This explains why step family porn and ecchi anime exist, and why they are so 
popular. We hate its brashness, we get over it mostly because of plot or more 
comfortable sexual scenarios, we quietly enjoy that "forbidden" aspect while 
pretending to righteously despise it, but we also justify it with "but they're 
not blood related". I wouldn't say this is universal, but it is common for 
people with a standard-ish heterosexual drive. Normal people, we could say.
The elephant in the room here, on a related note, is of course the attraction 
to children. Obviously this is messed up, it is "forbidden", and this is also a 
not entirely self-evident or consistent matter. We can divide the lolicon (or 
shotacon, or predator, whichever term you prefer: though there is undoubtedly a 
distinction) into two categories: the okay (slightly-confused) ones and the 
not-okay (scum of the earth) ones. The okay ones have a complex something like 
this:
They sexually identify as a peer to the object of desire. The "I wish I were 
her age" guys. These are the sort of guys those vigilante cringe youtube dads 
entrap and lecture. They're just larping, and they have enough other problems 
to sometimes take that larp to illegally serious levels.
The not-okay ones have a far worse complex: they enjoy exerting power over 
weaker beings. They enjoy being dominant over powerless helpless ignorant 
delicate beings. The sexualized form of the "tortures small woodland animals as 
a teenager and grows up to be a dictator" trope. That trope also has 
distinctions to be made, particularly in the case of Peter the Hegemon (of 
enders fame) who redeemed himself and actually turned out kind of okay and 
redeemed himself. But anyway. What makes these guys so hatable is their 
entitlement, that clouds even self-awareness. The smarter ones never get 
caught, or go free, because they spend all that extra brainpower protecting and 
justifying their sore-loser caveman drives. While the other type longs for a 
love that cannot be, these monsters have given up on-- or never knew-- love at 
all. For them, their actions are stop-gaps for the infinite hole of ambition 
and lust. I bet if one of these guys were to literally rule the world, and 
remake it in his own image, and fuck every single girl on her 9th birthday, he 
would still not be satisfied. Something made him this way, but this cannot 
excuse his continued pursuit of these desires. Okay, I think I'm getting 
extreme here. That example was too colorful.

* 2022-01-02 9:16 pm
Welp. Work is tomorrow.
Best thing I did today: disable mouse clicks in vim insert mode. Tiny thing, 
literally one character fix, but has bothered me for weeks. Also crushed the 
last of the cans I had brought to the car. Also texting dad was kind of a 
relief.
I'm gonna get my makeshift pj's on and fill out som MC Donald's receipts. Night.

* 2022-01-03 9:18 am
$2500 pay for December including Christmas bonus. Nice. Gonna live off $400 
this month. Nifty.

* 2022-01-03 11:23 am
#+begin_src
<story part=2 name="musings of a fly on the wall" >
As the Atheist left, he noticed a black mark on the dingy but clean beige wall. 
He smacked it and it smeared and died. The end. 
</story>
#+end_src

* 2022-01-03 9:46 pm
Best thing of day: cleaning apartment in preparation for bedbug heat death. 
Also getting paid was super nice. Christmas bonus ftw. In the morning I will 
leave my door unlocked. In the evening I will dine with Macklen. At the end I 
will return and reassemble my scattered belongings. I hope the laptops survive 
the fridge for 24 hours. Eh, should be mostly fine. Anime is a lie and I can't 
get enough. Good night.

* 2022-01-05 7:32 am
Forgot to say best thing of yesterday. How about, dinner with Macklen. Eh. Not 
actually proud of it, but nothing else springs to mind..

* 2022-01-05 8:18 am
Not going to work. Well, maybe in the afternoon when nothing will get done. The 
bugs apparently do not die when they are killed, so that has been unfortunate. 
I caught another one, but that was my only Tupperware so now I can't eat. 
Whoops. Probably will go for a nice long fast-food parking lot run and waste 
some fuel. For now, time to see if the laptops still work after being fridged...

* 2022-01-05 10:04 pm
Did nothing. Feel nothing. Cthulu and the futility of life burn large on my 
brain. Garfield is an eldrich god that torments Jon. Roko's Basilisk is a 
strawman fallacy cringe. All cringe is post cringe. We want to be Garfield. I 
want to be an eldrich horror. I care not for the lives of men. Let them die! 
This is my take on abortion. It is idiotic in the contemporary sense to say 
that the "fetus" is not alive, is not genetically distinct, is not ningen. It 
is idiotic in the Greek sense (selfish) to kill it. As far as facts, I take the 
simpler side: it is a unique and distinct human. As far as actions, I take the 
simpler side: it is expedient to terminate it for the sake of convenience. 
Thus, to murder. Maybe call it manslaughter. Maybe the term murder should be 
reserved for killing without motive, or without planning, or without properly 
weighing outcomes. Let them die. People should accept that intercourse leads to 
the creation of a new human life, and this is fine. If you want to sex that 
badly, go ahead. Kill it. Already, no one wants abortions. It is a backup, a 
last resort. Murder is always the last resort. With this model, we may fix the 
heart of the intellectual disparity - - albeit sacrificing the perceived 
morality altogether. But morality is already dead. It's 2022 after all. May as 
well kill it. It has no regrets. It deserves a state of eternal choicelessness 
more than the pain of earthly toil. Let it die. If it dares exist. Anyway. I'm 
getting too based to keep around. Better quit.
Best thing today: bought broom. Not using it, but bought it at least. Pathetic. 
What you will.

* 2022-01-06 8:45 am
Bright and early. Too late to change a thing. We waste so much storage here. 
Stupid one-time-write discs. We hates them, but actually no, they have their 
purpose. Ech. Ick. Itch. Scratch. Slap. Pinch and twist. r/goodnightreddit. 
Woosh. Will nothing rid me of this troublesome infestation! Let them die too.

* 2022-01-07 6:45 am
Best thing of yesterday: not giving up. Work was stressful. It always is when 
Josh comes in.
So today is Friday. Let's hope the exterminators actually come and do their 
thing. I wouldn't mind everything getting messed up if it means the bugs die.

* 2022-01-07 11:22 pm
Best thing of today: actually finished lunch. Miserable. I'm so fat. Also
Might not sleep tonight. The conspiracy theory iceberg has taken hold and I am 
haunted by those zipper demons that people on lsd see. Better re-watch 
transformers beast machines. Welp, that's some nice old mixed feelings 
nostalgia...

* 2022-01-09 4:17 am
Counting this as late night on the 8th. It's been a long day of moving things 
and doing actual work, so I needed a night of not sleep. Best thing of 
yesterday: getting the carpet. Also working up the courage to take blazer #1 to 
the dry cleaners'. All these have needed to happen.

* 2022-01-09 4:02 pm
It feels like a lot earlier in the day. I'm three hours shifted. Maybe sleep 
more? John Titor is super interesting. Definitely real. On and unrelated note, 
steins;gate was so good...
Washing all sheets because bed bugs. Curse them. I'm worried my mattress is a 
spawner. Which would suck. It's a nice and new mattress. Costed $400. I can't 
just toss it now... But I can't not. Man these things are the worst. At least 
they're not all over anymore. Hope this queen bed frame turns out okay. It was 
a little sus but should be fine... I am using too many ~...~ In my writing... 
Must stop. Well there's a woman reading in the laundry room and I'm a little 
bit worried. Society ruins any polite conversation that was possible, which was 
basically 0 already. Like, what does we say? You either talk about nothing, or 
plumb the depths of pain. Talking about nothing is painful too. Maybe that is 
the worse pain? The fear of missing out. Well I'm sort of above that. Breaking 
my back just to taking it back to the seventeenth track when none of us were to 
blame.....
~Breaking my back just to know your name~
~But heaven ain't close in a place like this~
~Anything goes but don't blink you might miss~
I don't miss I hit
Hit the target
Shame on target. Transgender bathrooms that everyone forgot about. Remember 
when that mattered? I do. And yet life goes on, nobody cares, and we pretend we 
are logical and learn from the past. You gotta hate it.

* 2022-01-09 8:55 pm
Best thing of today: washing. Also discovering animedl and the constant 
improvements to Ani-cli. Someday I will menu-atize it. So that it works with 
rofi, wofi, dmenu, fzf, anything else. And then make a custom menu script that 
just selects the one we want anyway. Also neovim status line manipulation is 
weird. I want to make vim the default graphical window for everything. 
Specifically nvim-qt or similar. Then this:
- standalone window manager with super key prefixed vim motion
- independent "bar" on top or bottom that contains vim statusline as seen in 
airline or similar, piped into the graphical window somehow
- nvim server going in the background
- new terminals are nvim-qt clients each with a new term buffer
- possibly put some shell alias or function that opens a new edit buffer while 
suspending/hiding the current shell/term. Then a ZZ gets one back. Everything 
still feels like it's in the shell, cause it is. But Esc triggers _real_ vim 
overlay editing rather than a hacky scripted shell vi-mode. \: triggers the 
full Ex command line of vim. The shell is always in vim, and has the properties 
of both vim and itself. This is similar to my previous tmux setup but nvim 
actually has useful features and extensibility whereas tmux is kind of bad.
So far from preliminary testing it appears that we cannot, in fact, "just 
werks" filename completion in the default terminal buffer. I many need to find 
a workaround... Also the block cursor is annoying.

* 2022-01-10 8:07 am
Only one at the office. Fhat a wucking joke. Jon won't answer his text messages 
yet. Guess it's just me! Better check the calendar. In a minute. First I want 
to ~consider this. The hint of the century. Consider this. The slip. You 
brought me to my knees pale. What if all these fantasies come flailing around 
and now I've said too much.~

* 2022-01-10 10:32 pm
Best thing: took a shower and killed a bug with my bare hands. They can be 
defeated. Also got dad to basically promise to give me a TV. In return I have 
to show him how the apt has progressed. Slightly nervous but whatever. Tired. 
Night.

* 2022-01-11 5:27 pm
Best thing: set up mtg with mom on Saturday, then going to dad's to pick up the 
TV. Will swing by Carrs on the way back and get some ice cream. In the 
meantime, apparently neovide is working again. Will use that. Night.

* 2022-01-11 9:39 pm
No bug sightings today. That's almost good. Kind of worried now though. Where 
did they go?
Took another crack at Awesome Window Manager. Not truly awesome. Maybe kinda 
nifty... I still don't get lua. I think in bash, config in vimscript, and 
scribble in markdown. The only thing that interests me in Lua is the ambiguous 
parens/braces/quotes. Everything is a lot more verbose and feels boilerplate-y, 
but that's clearly because you're generalizing to a really general syntax. It's 
trying to be minimal and light. It's trying to be Turing complete. It's trying 
to be an effective configuration method. It has to explicitly call the 
program's APIs in the same way that other configfile syntaxes can't. And still 
there are no tutorials on learning these things from a place of only basic os 
scripting. I am confused. These concepts make no sense. There is no type but 
the string, and the pipe is its one true operator! Take me back to TI-basic. 
Maybe I need an IBM 5100. Finally finished reading the logs of John Titor from 
2001. I basically believe him. Those guys who claimed responsibility were 
probably just riding the publicity. I don't blame them, except for being awful 
human beings. But whatever. I can't change the past yet, so let them have their 
fun.
Do I stink? Am I lazy? Is my setup jank? Or are we dancer? Haha hahaha so dumb. 
My faith in the Killers is gone after that song. We ain't human after all. Put 
all your blame on me.
There is indeed a plugin for neovim to put its statusline in the tmux line. 
This is fine except tmux is bloat. So, I found the tmp file it communicates 
through to pipe it into something else. Guess what, it's in a tmux specific 
format. Tmux has its own config language that is the worst of vim and sh 
combined. Must die. Maybe I can use some lua magic to make a vimlike statusline 
in the Awesome topbar? But the people are retarded. So says big man bigman...
Down to the wire
Fighting'z only begun...
No it didn't. I made edits in vim and they did t transfer. Clearly there are 
multi problem. S. Night.

* 2022-01-12 7:20 am
I had a dream. Maybe sort of scp related or something. There was a house with 
some special property and that kept coming up. The events were like youtu.be 
videos. I can't remember the rest.

* 2022-01-12 7:48 pm
Chatting with the GCI rep man on their website. This is $80 per month for 250 
gigs of high-ish speed. Fast enough, certainly. 200m down, 10 up. So bad but 
usable. And not relying on Dad. But also relying on the city. But can hopefully 
get bound to a public IP and thrown on the network. Let's see what they say...
I'm somewhat skeptical of their chat service. Weird fake message bubbles appear 
and disappear without any content, but then a real one shows up. I'm too fat to 
go to youth night. I'm a dirty old man at the age of 18.
The agent was being dumb about IP addresses. He was Indian.

* 2022-01-12 10:37 pm
Best thing: got a hand truck from Lowe's. Will use. Also got GCI set up to give 
me a router. $80 a month. Had trouble with specifics because the poor Indian on 
the phone isn't interested in the subject and wouldn't have access to the info 
I wanted even if he was. Also the illusion of his understanding English was 
shattered as soon as I mentioned IP addresses. But we did the transaction, and 
I got receipts by email so it's probably legit, and I get a free router. The 
worst that happens is nothing works and I cancel the subscription and have a 
random router lying around. But that won't happen unless it does. I must rest. 
Night.

* 2022-01-12 11:45 pm
Wall to put mirrors on is roughly 5x8 ft. A couple inches short both ways. 
Lowe's has them. I will go there after Saturday takes place. Till then I walk 
alone...
I cannot sleep I cannot dream tonight
The thought of missing out and not being with my "friends" still bothers me. 
Why is this so? We have nothing in common but some shared memories that are 
ever more remote.
I want them to live without me. I need to branch out. I am told this, I have 
said this. But for what? But the people are retarded. Stallman didn't die for 
this. Jesus didn't rise for this. Anything goes but don't blink you might miss. 
Cause heaven ain't close in a place like this I said a heaven ain't close in a 
place like this.
(what follows is a machine experiment from clicking the middle suggestion):
I think it is a fucking lie to me and I am not sure if I will be able to make 
it to the meeting and the other artist can copy his idea and I will have to do 
it to validate my account and I will have to do it to validate my account and I 
will have to do it to validate my account and I will have to do it to...
(and now, the leftmost suggestion):
Is the only way you do it right away with your default browser to make sure you 
keep your current settings and then you can see that it doesn't work for the 
most recent one that is the dumbest of your computer to be able for a week 
until you have to forward a certain port of your router or the new and actively 
maintained fork of the Linux community and human recovery software is the one 
you need a Mac for the first result in your computer and your reward system for 
your reddit and they will be able for you I'm not sure if I will be able for 
this is to reduce her or not be able for her and I will have a MacBook air 2018 
wifi is not a desktop environment unto the world with a lot less stuff to be 
done than to be able for a week or a week or a day or a day after you leave 
your house or you have a windows or bath tub or bath tub or a modeline that can 
be used for any type or size or space that is needed to make a USB port for the 
sake of the Linux community and human nature to be able for use in a calculator 
form to make sure that you have a windows operating environment and how to use 
for your own home security services or to use the arrow keys on your phone to 
use your distro's address and phone to use your personal name or address and 
phone to your web site to use your personal name or address and phone to your 
web site to use...
(finally, the right side prediction):
The people that are in charge and all of this stuff will help me get the right 
track to go with me on my phone to work in a calculator and then have a MacBook 
for me anymore because of how much money you need a better deal to make money 
with the bugs and updates you have the most best deal for the next two months 
is going well so we have to do with that in our future as a member of your 
business to help out a family with your business partner or partner who is a 
good guy for the most best selling products that are visually attractive to the 
customers who have a good sleep and can help them understand what they don't 
want them in a year ago when we have them on hand with a variety that makes you 
want more comfortable shopping with their products to make your business a 
better quality of life for the most affordable quality you are looking at least 
in the long game we choose from our collection to your favorite products or 
service providers in your home business or family
That last one just ends there. The prediction stops. The button is empty and 
does nothing. I find this curious but rather expected. And reading it back is a 
stupid kind of hilarious.
#+begin_src
1
11
21
1211
111221
312211
13112221
1113213211
31131211131221
13211311123113112211
11131221133112132113212221
3113112221232112111312211312113211
#+end_src
The sums are:
#+begin_src
1
2 prime
3 prime
5 prime
8 2x2x2
10 2x5
13 prime
16 2x2x2x2
23 prime
32 2x2x2x2x2
46 2x23
57 prime
#+end_src

* 2022-01-13 8:00 am
Just had a dream right before I woke up that I found Lillian by accident she 
had pulled into an alternate location of Charlie's bakery that was closed in 
closed down and I pulled in after work I have to her I asked hey are you lil 
she said yeah I think so why and I asked how life was going but instead she she 
asked me this question: "did you know that you can indent text documents.? 
Quote and I said yeah I guess and suddenly the building itself was what is a 
cube and the words were going along the sides of it and suddenly the building 
was clear you could see the forest through the back of it. I kept trying to 
redirect the conversation because I was curious as to how Lillian's life was 
going, but she just he just kept asking me I guess. It's hard to tell what 
happened, since the dream Illusions broken and I could feel my real body waking 
up. As I lay there I kept thinking take me back I want to know what what 
happens I want to ask her how she's doing I want to I want to ignore the Giant 
joint Calamity of the markdown parody. I didn't want this this isn't what I 
wanted no take me back but also okay fine whatever who cares but also know. You 
know? No you don't you don't I want to shine down in the hearts of man I want 
to take it from the back of my broken hats. I'll ask I'm breaking my back. Now 
I shall be late to work because I am dictating this in the car as you can 
probably tell just by reading it. Might edit later but probably won't.

* 2022-01-13 8:09 pm
Best thing: Jon explained me how IP addresses are assigned. Slightly mind 
bending but really rather ingenious. Also, I bought a big thing of milk and 
eggs and used my collapsible dolly for the first time. Not perfect, but 
wonderful. Man, this building 's history is crazy. You gotta wonder, what made 
him do that? Is the place cursed? Hey that's fun. I've always wondered what the 
mental landscape of a horror protagonist would be.
Read an idiotic article from Google recommendations. Basically, isekais are bad 
because SAO already happened and was kind of bad. I want to destroy it in full 
later but can't be bothered to find it. Here's some points they made:
- kirito was boring in his overpoweredness. Thus Rimuru and Ainz are even worse 
because they are more overpowered.
- Shield Hero promotes slavery because Raphtalia is a slave.
- the shows have long names. Long names bad.
- the tropes are tropey. Boring and bad.
- some shows (like re zero) are dark and dark = serious = not-for-everyone = 
bad.
- there are too many. Selection = bad.
- people don't like bad shows that are isekai. This causes controversy. Subject 
of controversy = bad.
- it's not real. Real = good. Non-real = bad.
Yes, I'm simplifying. But that's within sight of the actual thing. Actually, 
here's the link: https://www.cbr.com/harsh-realities-of-isekai-anime/amp/
Faith in humanity lowers just imagining it again.

* 2022-01-14 1:09 pm
Got back in touch with Charles. We're dining tomorrow maybe. Gonna make him 
carry the TV up with me.

* 2022-01-14 9:56 pm
Good day. Off work early. Tomorrow will happen. Best thing of today: swept 
apartment. Also listened to some hidden Luke Smith rants I hadn't previously 
been aware of so that was good. I need to start recording for YT again... All 
in due time. No router yet, might not be here till Tuesday. Argh. I will have 
to rewrite my website. Probably for the best as it's garbage rn anyway. I 
shouldn't say that. It's fine. Whatever.
Night.

* 2022-01-15 10:59 pm
Long day. Best thing: hanging out with Charlie. Worst thing: nah. The TV 
falling and breaking the stand is kind of bad, but fine. Work-around-able. 
We're leaving together
But still it's farewell
I'm really tired
Good night and oh well.

* 2022-01-16 4:30 pm
Christopher emailed me this morning. Wants me to join some Bible group on 
Saturday mornings and come back to mass. I didn't respond and probably won't.
 Charles Charlie God lies truth noise confusion apparently I'm scrupulous now 
so that's what we're going with I don't know I can't tell everyone else is 
wrong I don't want to be like them but I want to be understood and appreciated 
and loved and known I want to speak and be heard I want to bless them with my 
knowledge and ideas I want to write the dictionary I want to organize I want to 
extend I'm tired. Taida desu. Charles said he'd watch Steins gate, let's see if 
he really does. We might hang out next week. He knows my YT channel. Let's hope 
he doesn't watch the vlogs where i rage at him. Ah well. Then he's a fool it's 
just as well hope it gives you hell.
Should I start trying? Or is this the way of madness? What do you know, haw far 
would you go. You're gonna go far kid... With a thousand lies and a million 
truths ~I'm gonna make it bend and break so say a prayer but let the~ bad times 
roll
~And I want these words to make things right but it's the wrongs that make the 
words come to life, well who does he think he is?~ The worst thing I could say, 
things are better if I stay.

* 2022-01-16 10:44 pm
Best thing: setting up TV? Laundry? I did work a little on tmux and that kind 
of thing. Maybe I should do more on that here. Okay. Night.

* 2022-01-17 8:46 pm
Best thing: merging most of the vim files together. Buying new keyboard.
Ate way too much. I almost want more now. It's either that or jacking off 
again. Checked back in on u/KasaneTeto_. He's doing okay. Seems to have 
mellowed slightly. Someone else expressed the same wistful longing for his 
presence and got accused of Stockholm syndrome. Garbage take. There's more than 
that going on. For one thing, the relationship isn't like that. There's a 
genuine draw to people like that, especially through a textual medium, and 
those who deny it tend to deny it so hard because they feel the pull but reject 
some part of it and take this personally.
What is curiosity? Do I love it, or hate it? Is it good or bad? Bad, 
apparently. I love it. It's sort of an addictive taking of knowledge, a 
hoarding as it were. Even if I have no one to ask, I will observe that I may 
know, and I will grill those around me to find the answers. It is arbitrary. I 
don't want all the answers to everything, just what I'm sort of interested in. 
This is the whole thing with Echidna. She craves knowledge. The mental model. 
The perfect chart of cause and effect. This is the value that Subaru has to 
her. And indeed, the value that Mom had to me was lost when she ran out of 
answers. Charles is ananytical or BS enough that I can keep asking him the same 
question and he will drop more exposition every time. Jon is a river of info 
which I can barely drink from. Subarashii desu. I don't know. Should I know, 
even? They say curiosity caused the Fall. The weighing of uncertainties. The 
first ill-placed bet.
~Great king rat was a dirty old man and a dirty old man was he! Now what did I 
tell you, would you like to see? Oh~
Every story I tell has some fantastical element. It always falls out as a 
battle of wits and morals and ideals with uselessly high stakes and 
based-but-wrong characters. The house can't burn down, or if it does it wasn't 
that bad, but if it was that bad the most interesting character escaped down 
the trapdoor into the cave system of their secret base. The mystery is 
semi-obvious but will be very spun out and contribute very little to the final 
battle. The characters and setting bend over backwards to not stray out of my 
areas of extra knowledge. Pacing is done by intercutting scenes of new 
characters.
I refuse to call my rhymes poetry for that they are not. Poetry should be good. 
Sure, most of the stuff you get in high school is kinda bad or total garbage, 
but there is a goal and a self-respect one must work towards.
Inevitability. Ironic unirony. Subtle and integrated blatant absurdism. 
Ambiguous backstories so I can make up the past as the future stumbles along.
And yet, "oh you're a genius your stories are the best how do you write so 
well" I remember a tiny bit more than you, I treat every missing piece like a 
side quest to be completed by accident, and I push through the self-doubt of 
creating flawed work by propping myself up on your praises. It's not hard. Not 
noble, but not hard. Just a front. A convenient subsystem. Almost emergent.
Vim needs to become like emacs. A complete system where everything can be 
redefined. Write it all in lua, see if I care. Make the viml interpreter a lua 
plugin. Nvim the executable will be but a lua interpreter with base os and 
terminal-control api builtins. The modes will be lua states. Their letters will 
be dictionaries. The ideal statusline plugin will just ask for the name of the 
current mode and put whatever in. It will float and be movable to anywhere and 
bind to anything. The pane/tab/window format will be guttable so we can just 
forward the calls to the desktop to spawn a new gui. No awkward mappings. We 
can define every key as default and redefine any as needed as if from scratch. 
Like qutebrowser. This is my dream.

* 2022-01-18 10:26 am
Wore the white socks. My feet are throbbing. That whim alone will make this a 
bad day. Maybe. The router is supposed to be delivered, so that should improve 
things slightly. I need to skip lunch. Ate too much yesterday and this morning 
and I want to have Mac n cheese for dinner. How will the website work? Thing 
thing, maybe? Sshfs? Just plonk services on top and hope they mostly work? 
Docker? So many options. Definitely markdown. Definitely an internal network. 
Peertube is a thing. Just forwarding hosted files is also a thing. I want to 
re-encode everything to stream lightly as possible. But keep it on that 
computer. Which will become a sorta desktop. The active laptop will become the 
L13. I reckon the chonktab can stay as a Hotspot. As long as it has an 
ethernet. Pretty sure it does. If not, E585 does everything. That would be sad.
I need to try vm clustering again. Using sshfs. All the things.
Neovide as the terminal has been a good learning experience though. I dig. The 
only problems are cursor-shape and the occasional oof of getting hung up. 
That's mostly my fault for bloating up vim. Which I maintain needs to be 
rewritten entirely in lua. But whatever. Man my feet are throbbing. Not a big 
deal but is annoying.

* 2022-01-18 10:14 pm
Best thing: nah. It was a bad day. I wasted another's money, ate way way way 
too much, didn't get my package-- inexplicably. Eh. Probably a garbage 
underpaid postman. I told Lael so hopefully that will resolve itself tomorrow. 
Generally, everything today was a disappointment. Not happy.
But if I had to pick a best thing, paycheck? No. Capturing bedbug? Not like 
that will lead to anything. Um, watching Cowboy Bebop? Sure. It was good.
I don't feel mad or even really disappointed, just tired. I'll stew in my 
overstuffed thoughts tonight.

* 2022-01-19 7:51 am
Good morning. Whatever that means. I won't go to McDonald's today. I'll try to 
skip lunch. Will go to youth night. Unless router comes? Nah. Not like I would 
know anyway. Need to deposit paycheck anyway.

* 2022-01-19 10:46 pm
Went to youth night. Was chill. Router came to the door so that's all set up. 
TV stand is broken, but I ordered a full good one on Amazon. Spent 50 extra on 
faster shipping since I don't trust their long option. Got double rent in 
Savings because I don't want to fall behind. Will hang out with Charlie Friday 
at 6. He's started Steins gate and is enjoying it. Hooray. Best thing: making 
everything work out. I did the stuff and life delivered. Good night.

* 2022-01-20 8:37 am
Woke up early and semi-dreamt of a chill philosophical wakeup. Then my alarm 
went off. Moved the craptop to underneath the table that now has the TV on top 
of it. This will age super well at the end of the year when everything is 
different. Ej, it's good to remember they say. E585 is connected to the new 
wifi. Now I need to work out my optimal network setup. The idea is that it 
works. Maybe forward different ports to different places? Obligatory mention of 
sshfs for being the best thing ever. Charles says he's got a spare couch. I 
secretly want some sort of portable couch-like thing that is couch-y but 
portable. Not the banana. The banana won't work and I have no idea who thought 
of it. Gabe did. Why? Is he dumb? Nah, he just hasn't actually used one. It's a 
true meme product. Useful for its own thing but not much else. Like most 
things, but it's own thing is less important so it feels more wasted. Ech. So 
much trash. Trasn in my car in my house in my mind. Abcdefu.
And now it's morning. Jon's not here so I'm all alone. Better off all by 
myself... Nah.

* 2022-01-20 10:11 pm
Vim wiki was sorta broken so I switched back to vim-plug to make it work. 
Configuring apache/httpd is going to be sort of tricky. Not too worried, just 
sort of annoyed at the many pitfalls of fixing-up this setup needs. But hey, 
we're aiming for effortless singularly by the end.

* 2022-01-20 10:39 pm
Best thing: learning vimwiki. Great system, actually makes sense. Good night.

* 2022-01-21 8:46 am
/Narrator: 'it was not a good night.'/
I stayed up till 3 am working on ports and ssl and all that madness. As it 
stands my http works, but https does not. Trying ssh now.
Ssh works. Hmm. Should I reboot? I'll reboot. Nah. I won't.
Didn't reboot. Of course not. I'm going to install Debian and put my dotfiles 
on there so this starts working. Setting everything up on artix is ridiculous.

* 2022-01-21 10:33 am
Debian image is downloading. In a tmux pane. Yay! Paru! Apt! This is some 
garbage and I will have to work on that setup script. I really don't want to 
though. It's confusing. In less than 12 hours I will be frolicking with 
Charlie. Where how can I be awake then. With lots of subway. But we're getting 
McDonald's today for lunch. That works out. That's fine.

* 2022-01-22 6:24 pm
Didn't hang out with Charlie last night. He canceled when I was literally at 
the door. Says he was tired. We had a good talk today though. 
Best thing of yesterday: getting all the pieces of the server up and running.
Best thing of today: real talk with Charlie. We watched episode 6 of Steins 
gate and half of episode 7. Right up to the bit where he wins the lottery. I 
think I sort of spoiled Mr Ferdinand Braun, but he's on his toes. Or is 
pretending to be to help my conscience. I told him I was sort of worried that 
he had given up and had 5 girlfriends or something. He doesn't. He's going to 
confession tonight for the first time in like 8 years. Was stressing. Hope he 
works through it.

* 2022-01-23 9:45 pm
Went to mass at st Andrew's. Exactly how I thought it would go.
Best thing: made myself go to mass? Took shower? Also wrote half of the 
web-scraping article. Aight time to laze and sleep.

* 2022-01-24 10:14 pm
Okay day. Best thing: research for Tier 1 of computer iceberg.

* 2022-01-25 7:11 am
2 dreams last night:
1. I went back in time in Anchorage. A hundred years but also a thousand or 
something. An ancestor of Charles was there and so was Elon Musk who had 
invented cars way too early. I told him, won't this mess up the time line, he 
said nah, it will but who cares. There were 2 instances. 3 jumps. I used a lot 
of mobile data in the first one. Talking to Charlie. I noticed discrepancies, 
talked to people, and worked around them. I got booted off and had to return 
but it wasn't a big deal. The third jump I was Lillian. I went to the women's 
bathroom and it was melty like Styrofoam and had negative gravity. I was naked 
but there was a large pile of towels. Someone came in and I had to hide myself. 
I behaved as if everything were as I expected and got chased away like any 
other isekai. It somehow didn't feel like I was lacking critical information, 
or even doing anything stupid. The setting of this all was a 2 storey motel B&B 
where the welcome to Anchorage sign is now. It was orange like Arizona or Mars 
but more yellow and not particularly temperature.
2. The loner badass OP protagonist is in an isekai with several girls. One of 
them has a move where she jumps high up and hits the monster really hard with 
something in her left hand, and quickly tucks her short-short-skirt back down 
with a smirk. For some reason there was tension between her and protag-kun. So 
he is training her or something. Doesn't want her body. Is the assumption. So 
she twists everything into a hyper sexualized position and he just kind of 
ignores her. Until one day he decides to punish her. What punishment? I don't 
know. I disconnected from him and started waking up. Probably something cruel 
and pointless. Like cult leader crazy. Like that moment in the music video for 
you're gonna go far kid where leaf lady goes yuck. That's how it felt. He 
abandoned all relatability.

* 2022-01-25 8:25 pm
They sprayed my baseboards again. Good. Let the bugs die. I found some 
carcasses.
Still haven't shipped my TV stand. Charles can't bring the couch till Saturday 
maybe so that's a minor bummer. Bought pj pants and underwear and more cheeto 
Mac&cheese. Ate some already, now I'm very full. Jreg is so post-based. It's 
too hot under here. They're thick pj pants. Best thing: worked more on iceberg.

* 2022-01-26 10:48 pm
Best thing: youth night and got Mikael tentative for next Friday. The one in 9 
days. We'll see what a godless nation we have become. I'm thoroughly tired but 
want to chill awakely for a bit. Might not be wise considering the morning to 
come. Josh says he'll be in 8:00. (X) doubt. Not working on website or iceberg 
today. Gnight. Worst thing: YouTube comment arg on old back to the future pitch 
meeting. These people are difficult to discourse with and I shouldn't bother.

* 2022-01-27 8:55 am
I guess I'm happy. Well worn out from last night, and Josh is awake but not 
here. Basically it's a perfect day in the morning. Gene and Jon should be here 
around 11 or 12. Josh says he's showing up but I doubt that too. I should stop. 
He seems okay today. Whatever. Not my life. Maybe it will be...
He just wanted the calendar. That's fine. Sent to him. We good, we good. 
Seriously need a vim keyboard for Android. And neovim to be rewritten in lua. 
Let me do some research...

* 2022-01-27 10:36 pm
Not a very good day. Work got miserable when Jon showed up. I love la Cabana 
but hate how their food makes me feel at work afterwards. So heavy and slow.
The search for a truly extensible editor has led me through some rabbit holes 
regarding the nature of line breaks in files, and some alt-plan9 forays into 
array-based text editing. And ultimately back to emacs. I'm giving it a try 
again, this time with System Crafters' tutorial. Might be good, might not. Who 
knows. At worst it's scriptable notepad, at best it's the best thing ever. I 
just hope we can fix the fakeness of the GUI before it gets any more 
entrenched. They say everything in Emacs is re-definable so it better be. At 
worst we tear it all down and disable all splits and forward it to the OS.

* 2022-01-30 1:51 am
Whew. What a weekend maybe I guess.
Best thing of 1/28: Josh came in and got that client some help. The one that 
hates their previous lawyer and can't get a job because background checking is 
unconstitutionally broken.
Best thing of 1/29: bought a homeless woman some Wendy's. It was awkward, but 
it felt good. Kind of. Also put mirrors up finally. Need to go to Lowe's 
tomorrow to get more.

* 2022-01-30 8:50 pm
Mirrors fell down in the night. Spent all day cleaning the glass up. Sucks.
Finished CowboyBebop. Good. Watched the incomplete second season of 86. Okay. 
Ngl the whole gritty-war-battle isn't really my thing, and a lot of what I 
enjoyed from the first season was missing. It's a good continuation, but in my 
book 86 ended after the original run.
Worst thing: having to clean up all that glass. Generally a rather rotten day. 
Ate a double batch of cheeto mac. Ranted straight onto my website about it too. 
[[./articles/idkman.org]]. Had a crazy dream last night but whatever. Not 
really ready for tomorrow. Jon will be cranky and resigned, Josh will be in a 
convenient coma, gene will be crazy, and I will be heavy and irritable. Much 
water will be drank leading to heavy peeing in the afternoon. I will reject la 
Cabana when it comes down to it because I can't work afterwards. Good place 
just not time for it. Eating there consumes the whole day. I'm so fat. God I'm 
so fat. This healthy gamer doctor k guy seems chill and smart. Some of those 
patients are a lot like me but different in respectable ways. Finally someone 
else who can be allowed to exist in the new order. If that's what a therapist 
is like, then I want one. But I've heard bad stories, and I've made them up. I 
have a theory about manipulation and the human condition that ties into this as 
well as Charles and everything else.
Best thing: letting random lesbian in just now. She dialed the wrong door code. 
I answered and she hung up. I went down anyway to check. Her gf apparently 
locked her out. I believed her and let her in and rode partially up the 
elevator. She's in 109. Hope that worked out.
Yesterday with the homeless girl. I could have gotten her to have sex in 
exchange for a meal or money. Why didn't I? 1. She smells like cigarettes. 2. I 
was nervous and didn't know how to chat with someone like that. 3. I'm out of 
shape and want to save the first time. Do I? Do I actually care? I swear it was 
like an anime. Never came up. I thought the real world was darker and grittier. 
She wanted to eat inside. I think I creeped her out but she was too desperate 
for food. Would have liked to have an actual convo with her but again. Awkward. 
I felt really guilty for already being full. Still bought a ton of food after 
though. Like I have no shame internally. I guess I should have gotten her 
number or something. I saved her from that security guard. He was a Huell type. 
Would have dragged her away and apologized for the inconvenience.
Gonna make a list of anime to watch next so I'm not blindsided. New note, 
creating now.

* 1-30-2022 10:40 pm
Here's a pill to rival the bog-pill: the beggin-pill. It is this:
The song "beggin" has existed for the entirety of humanity's history. It was 
sung by cavemen whose cave-women left them, and has been passed down the 
generations as an artifact of culture. Everyone has heard some version at some 
point in their life. In recent memory we can pinpoint specific instances of its 
evolution due to digital recording technology, but none of these groups wrote 
it. No one wrote it. It is the perfect encapsulation of masculine regret, and 
is a universal constant. It will continue to exist as long as its protagonist, 
that is to say, forever and different in the minds of each whom it touches.

* 1-31-2022 10:38 pm
I was led on down a rabbit hole. Now I must plumb it, the depths of it all. I 
began to watch Redo of Healer. By all accounts a mess, a vile mess, a highly 
dark and sexual work. The kind where you don't think the author could possibly 
write a wholesome or compelling story afterwards.
Only 4 or 5 episodes in, but here's my intermediate verdict:
The Healer is halfway between me and a cult leader. I know which one I'm 
referring to. I sort of grasp how he became as desperate as he is, and I long 
for that revenge right there with him. But the sexual aspect perplexes me. It's 
sort of like the rest: an aspect. Yet he gaslights too, especially about that. 
Extremely manipulative. In a very stereotypical way. But very dangerous. If I 
shared a universe with him I would need to kill him. But then he'd just rewind 
time and ass-rape me. And make me his bitch boy slave pig. Which I guess would 
be fine. At least, he'd make me believe it was for the best.
This honestly feels like a darker version of Shield Hero. The parallels are 
obvious so I won't state them here. Ack now my brain is trying to 
alternate-history-novel a Redo of Shield Hero. I am disgusted. Looking for an 
excuse to say "taida desu ne" but can't find one. Truly slothful!
Healer-monster wants sex. He craves it, to him it means power. Which makes 
sense. He isn't coming from a vaguely post-Christian internet-age setting, he's 
a fantasy character with roots and a kinda mom and an understanding of the 
magic system. Great excuse to not explain things BTW author-San, if you ever 
read this. You won't. Because I have no redo. I can (not) redo. No sign but 
Jonah.
Anyway.
Best thing of today: work went well. Deposited checks for Josh and returned 
just in time to leave. Jon apparently had a headache, but it's fine. Tomorrow 
is la Cabana. I have to not eat tonight or in the morning. Nothing until lunch, 
and nothing after. It's way too much anyway. Already. I am tired. Satisfied? No 
clue. What a terrible phrase. In preschool there was a kid who said no clue all 
the time. He was tall(er than me). I hit him with a death snowball once and he 
didn't quite die. But now I have an aversion to snowball fighting. Hope he's 
okay ish. Hope he got a clue.
Night.

* 2022-02-01 9:51 pm
Finished redo of healer. Wow, wow wow wow wow. Terrible. The sum of all 
depravity. Needs another season.
His revenge isn't ordered, or logical, or even really fitting. Well, maybe it 
is, but that would almost have to be a retcon at this point.
What is sex to the Healer? A method of control, of torment. A reward, a bond, 
an indulgence, a power source, a workout. A whim. A gloat. The indirect object 
(Latin Dative case) of gaslighting. The adverb of payback. The subject of any 
sentence with a simple "is" clause. It's basically everything. Anything. 
In this sense Redo is like all porn/hentai/etc-- the sex is an authorial 
indulgence, contrived into the plot. And yet, it is also a real and potent 
tale. The sex isn't just a punchline or collapse-state, it has real causes and 
real effects. The people participating are real and fleshed-out and have lives 
that led here and will be affected by this. The demon princess masturbates 
because of her shame and hopeless-heir-in-hiding complex, combined with pent-up 
confusion. Healer has a threesome in front of her because he wants to shock her 
and loosen her up and get everything on the table. He doesn't go for her 
because he sees her as an ally and not a pet or slave. She did nothing and cost 
him nothing, so exerting his _ore_ would be... What? What standard does the man 
have? Something of an aesthetic class. Useless and un-fitting.
Is this a deconstruction? The negation through over-concentration of 
whatever-excuse-for sex? I don't think so. It's a lot like what it looks like. 
Power fantasy revenge rape harem. That is its genre, its mood, its essence. And 
yet it does this archetypically. As if nothing else yet has or will. The 
contrivance is precisely on the border. Interspecies reviewers was firmly on 
the outside-- a totally contrived plot, a transparent excuse to be generically 
lewd without saying much of anything about the framing device. The sort of weak 
repetitive almost-porn you can sit there for hours with, pinching the shriveled 
sheath of your manhood and slapping your thigh without thinking much of it.
We'll have to wait for it to finish, but end of world harem looks to be the 
opposite extreme. A simple and plausible contrivance, and the inevitable 
necessity it brings. Like, it would definitely happen.
Reviewers can't happen because of real life. End of world harem has to happen 
because of human nature. But Redo is different. It is character driven. It is a 
sharp rebuke of the kind of people that Healer hates, that we hate. It is a 
tacit but nuanced agreement with its protagonist. It is a fractal. He gaslights 
the girls and he gaslights us by showing that. By the end, I was with him. What 
does that say about me? Are we really that different?
Best thing of today: signing up for Extra. Credit score thingy-izer. Oddly 
enough, the sponsor on a Zach Star sketch about watching xxx for the plot.
I need some sign that there can be a better future. This rabbit hole is a 
vantablack rug and I stubbed my toe on it.

* 2022-02-02 7:30 am
Last night I dreamt that I was a replacement actor for Shinji in an extremely 
high budget Evangelion live-action movie. The other actors had been studying 
and practicing much longer than I had, and seemed to fit their roles better. 
They kept assuring me that I'd be fine, to just be who I thought Shinji was on 
set. I wasn't familiar with the set or props or other actors, it was awful. The 
others never broke character. So I didn't either. I channeled that nervousness 
into a shinji like grim pragmatic wimpiness. Thus acting out of character by 
getting in the robot, I guess. That didn't occur to me then. Huh.

* 2022-02-02 10:45 pm
Best thing: real talk with Charlie. Discussed religion, basedness, and the 
Healer. He is hopeful but still believes that only Catholic/Orthodox is right 
and accounts for everything. Does not understand / accept my "understand every 
sin and sinner" mentality. Not sure I do either.
But I want to understand. I want to emphasize. I think I understand Hitler 
already, maybe Stalin too. From what I know of their histories it seems to make 
sense.

* 2022-02-03 11:10 pm
Finally doing the emacs theme right. This could be good.
Tiring myself out with heavy work and light anime. This could be heaven and 
this could be hell.
Best thing of today: sitting down after the whole move-all-change-of-pleas 
affair. It felt so good and relaxing.
Man I really want that couch. Charles...

* 2022-02-04 10:58 pm
Emacs is going well. I may switch pretty soon. The canned org-html copypasta 
seems somewhat broken, but individual file export works fine. Tomorrow I may 
try magit. And then? A fully literate config? It would be good to go document 
everything and trim out the unnecessary bits. The built-in terminals of Emacs 
are fairly disappointing. Barely even 256color, curses apps are broken, 
cursor-shape is overridden by emacs itself, pasting is hacky, and their names 
and distinctions are pretty confusing. I mean, we all know the best terminal is 
an actual terminal, but what we have is 1.75 single-line ptys with broken 
scrollback, a semi-okay 8color shell host, and a re-implementation of the 
coreutils with an annoyingly different syntax. Only eshell (the last one) shows 
any promise for the fabled intellisense pop-up command/argument completion, but 
that has so many other issues already that it leaves me very confused. Also 
it's still basically just a line editor with visible history. Forget about 
ncurses. Agh. Sorry not sorry for the rant. This is a pointless setback. I will 
have to write my own emacs shell-host from scratch once I comprehend lisp. It 
sort of makes sense, just not from both directions. I can read but not compose. 
Still thinking in shell.
Charles should be getting that couch over here tomorrow, and Dad might show up 
or want to eat somewhere. It'll be a day.
Best thing: finding/installing yascroll, the emacs text scrollbar. That gui one 
is dumb and broken.
Wow I'm useless. Did nothing today and won't be tired yet.
Good night.

* 2022-02-06 1:17 am
This counts as last night because I'm still awake from that day.
There is hope for emacs. Nvim will take decades to catch up at this rate. 
Especially since evil-mode already exists.
Best thing: watching the Iruma-kun arc where he turns evil. There's just 
something about how it was built up from the first season finale, and he's 
keeping all the connections he made as a hapless pushover, and he actually 
takes advantage of it all. It wouldn't have worked if he'd been like that from 
the beginning and pretending. Interesting. I guess that happens to me too, just 
on a smaller scale and it's always too late in the day to be of use. I'm 
strongest and smartest when it's mostly dark and I'm on the second can of dew. 
The most I've done for my tomodachis was at that point, the most daring 
adventures, the tallest bluffs. I stop third-guessing myself and use all of my 
mind. And yet, taking in new info is harder, and any bodily function wrecks the 
flow way more than usual.
Met with dad today. He's been doing a lot for work etc. Says I should Def do my 
taxes. Bought me groceries and lunch.
Still no TV from Charlie. I texted him about it saying it's okay, but I wrote 
"daijobu desu" instead. Ultra cringe. Whoops. Whatever. Daijobu desu.
I have a minor ache in the left side of my head, I feel heavy, and my eyes are 
a little dry. Shikashi, I am fine. Perfectly single-minded.
But tired. Still, it's been too much dew today (6 cans total?) so I couldn't 
sleep if I tried. May as well write.
#+begin_src
<song name="father to son" artist="Queen" >
Take this letter that I give you
Take it sonny hold it high
You won't understand a word that's in it
But you'll write it all again before you die.
<solo/>
</song>
#+begin_src
Man, html is nasty. Really got to switch to Org Mode.

* 2022-02-06 9:29 pm
Time is crazy. I am sorta tired. Today was mostly pointless. Watched a bunch of 
Emacs videos. Began the Great README.org Migration Project with my zshrc. 
There's still so much to unravel from this ecosystem, and get used to. It's not 
vim, even if it does an excellent job pretending to be.
Best thing: took out trash. Worst thing: this anime is so slow and light and 
silly. Admittedly, its jokes all hit and it's a good watch, it's just not 
really the mood I'm in. Hey, Charlie responded and didn't seem disdainful, just 
tired. He probably still has a life. Hmm. Guess I do too. Today is the day that 
is a day. Meaning nothing, signifying dessication. An idle and fruitless 
masturbation. Clouds in the shape of arrows, pointing at the omnidirectional 
horizon of forgetful blasphemy. Shakable unshakable glowing glowering showers 
from towers of the powers' prestige. This is writ ironical. Watching Redo of 
Healer has changed me and not for the better, maybe. A grim reminder that 
Shield Hero was a great show and true porn has no production value. There's an 
isekai parody on hanime and it's literally a sideshow. No flow or story or even 
a voice for the MC. I'm almost certain that all the girls are voiced by one 
person. Not because of how they sound-- they don't sound like anyone or 
anything really-- but that would fit the theme.
Okay, I'll just say it. It's been too long and otherwise it'll never get said.
In video-form pornography of all kinds, the sex is the only thing that matters. 
All that should be (though should itself is problematic in such a context) 
necessary is the sex itself. That is the essence of the genre, and the closest 
thing it has to a societal role. But oreitachi cannot live without some sort of 
plot, nor some petty disregard for the constructs of society, so plots are 
devised to frame and justify and contextualize the sex. And these are 
intrinsically lazy and nonsensical and repetitive and pointless-- for they all 
converge in the same place. The sex. Which itself is also nonsensical and 
repetitive. And so we have a curious phenomenon emerge: the plot means nothing 
apart from the sex, and the sex means nothing apart from the plot. In this and 
no other genre, the ending is completely and intrinsically inevitable. Showing 
and fully indulging in its defining plot point brings the story to a complete 
halt, and in many cases all consistency is lost now that the sexual portion has 
begun. From this point the only things that can happen are minor interruptions, 
new fuckers joining in, random cuts to a change in position, or The End. Which 
itself is only slightly less inevitable: there are now 2 possibilities. 1. The 
cum ending. 2. The shame ending. If there is a sequel, it will doubtless be a 
repetition of the original, for a straight continuation would have no plot left 
to cling to.
But this is the sinister bit: sex as a plot device can mean anything, nothing, 
everything, all at once. Maybe it's an indulgence. Maybe it's a rite of 
passage. Maybe it's a punishment. Maybe it's an accident that they just go 
along with. Whatever. It's the answer to wherever the plot's conflict happens 
to be when they calculate that the viewer is beginning to lose interest. So the 
plot has to be simple or inevitable enough to at least somewhat justify the 
singular waveform collapse. Just as Marvel has its sky-beam or Star Wars its 
spherical planet destroying laser or isekai has its demon king.
I don't feel like thinking about this anymore. Taida desu ne. Oyasumi!

* 2022-02-07 10:02 pm
Tired. Stressed. Too much or not enough, constantly bouncing between. What even 
be?
Best thing: made omelet for real for the first time in the new apt. Got 
paycheck. Didn't go buy ice cream even though I was all the way out in Eagle 
River. Ah well. I'm going back on Saturday to help mom move. That will be a 
struggle.

* 2022-02-08 10:14 pm
I'm okay. I'm not okay. Well, mostly okay. Emacs continues to exist. That's 
fine. Did a few things today and they all worked except editing over ssh, which 
is a problem with the underlying OS and not a big deal. Best thing: accurately 
described Josh's color pallette and explained why he should have worn a white 
shirt. He wore blue on blue with a green tie. To Federal Court. Ah well. At 
least he did something today.
Emacsclient -c is what I want. It launches a new "frame" which is a graphical 
window on which are drawn... Let's just do a stack hierarchy.
Linux Framebuffer 
Wayland compositor
Xwayland - Wayland client, x server
X client window: emacs frame
Emacs windows - may-or-may-not be made out of text
Emacs buffers - just like vim buffers. The editor's localized copy of the file, 
rendered as mostly-text with some inline images or pitch variation. The former 
is janky and needs work, while the latter is perfectly implemented. Except for 
window sizes with variable width fonts in the terminal! That's right, they 
really did just go "hey let's communicate everything as text and when we get 
thinner text just put more spaces in so it kinda lines up and fix it in the 
toolkit". Come on.

* 2022-02-09 7:16 am
Just woke up. Dreamt of the Disaster Leg: a copypasta and human benchmark. 
Associated with the new year and a lot of other things too. In the dream I 
drove to HRA's new location in the Jitters mall in Eagle River and read the 
outdoor signs. I did the homework from those. I entered the entryway which was 
Carr's and Morris and Murray cornered me. I said, hi I'm back and they said, 
you're going to need to do a lot of catching up. I said, I did the homework. 
Turns out they hadn't updated those signs in over a year. Huh. I went to Jon 
and he gave me a page written in Courier New and said "write this in one page 
for a bonus". So I scanned it as a pdf, copied the text, did some formatting so 
it all fit on one side, and gave it to him the next day. That was the opposite 
of what he meant. So I had to hand-write it in a hurry during a crafts session. 
We had fine tip kiddy markers and one of them looked white but turned out to be 
cyan, and then everything white looked cyan in the dream for a while. Anyway, I 
wrote it out on a thingy, and he read it and was surprised but said it was 
alright. The text itself was about the guy and the demon lord who was a white 
dragon snake with the head of a catfish. The third-tier giant evil dragon said 
to his master from the shore 'I don't think he's here: the humans have so many 
apparatuses set up in this lake etc' and his boss didn't believe at first but 
then did. Immediately the maou came up out of the water and there was a battle 
between him and the dragon. A human who had clear yellow skin and no genitalia 
walked along the floor of the lake. Something happened and they lost their leg 
in the disaster but everything else was fixed. So goes the tale of the Disaster 
Leg.
I'm missing something. That was weird. Why did I remember? Oh well. Might tell 
Charlie if he shows up tonight. If I show up tonight.

* 2022-02-09 10:41 pm
Went to youth night. Got pretty tired because dodging. Context is fleeting. 
Whatever.
I asked Gabe for the forms to be an adult helper since I'm old now. He said 
okay go to the website do the things sign the form drop it off. I need to tell 
him to have someone be there to do that because I work till 5. I should not 
have mentioned that I dreamt I went back to HRA. He responded with, "that's 
creepy" or something similar. Don't remember the exact wording but it was 
extremely offensive in an offhand way. Now I'm scared to do the stuff and mad 
at him for saying that and ashamed at continuing to go and worried about not 
coming back. I don't know what to do. Should I switch to Esto Vir or something? 
Should I go to Christopher's Saturday thing? I'd have to go to mass too then. I 
need to vent at Mom. That's my one real worry now. But she keeps eluding my 
grasp. With small talk and power plays and oblivion. It's all in my head 
because there's nothing in hers.
What mortal sins am I committing? Besides the main one. Somewhere in here is a 
way out. All tangled up in scheduling and connections and patterns of thought. 
I hate that. Why can't I just be a brain in a jar. Stop having to translate 
everything all around into the trivial all the time. Just because I can parse 
any English expression doesn't mean it's enjoyable, or should be necessary. I 
hate it. I hate knowing the most. I hate not getting to flex that knowledge. I 
hate the suspicion that we're not understanding the same way in a conversation.
Wow. What a Regulus Corneas rant. And I like him will die an immortal virgin. 
Virgin is such a weird concept. It's desirable but embarrassing. A physical 
distinction with social exceptions.
I'm falling asleep just trying to come up with words so bye.

* 2022-02-10 9:41 pm
I have nothing to put here. I have saturated myself with information and 
experience today, but I am satisfied. Nothing is right but nothing is wrong. 
Everything is redefined lisp expressions anyway. Everybody's are stacked 
different.
Best thing of today: that Graham cracker in the morning. With the water. Peak 
snack right there. Refreshing, slow, and sets a natural limit on itself.
I tried out EXWM today. Needs more configging. Has promise, especially with the 
next version of Emacs going pure GTK. Maybe we can throw a Wayland compositor 
on there soon? With wlroots. I genuinely have hope. I mean, it's already got a 
window manager, an init (sort of), an editor, a browser, a shell, and lots of 
games. If we get a good Wayland module it will be feasible to rip out a lot of 
the middleware. And then? And then we have an emacs OS. The Linux Kernel, 
`mount`, and emacs. As it is now the main issue with using straight emacs is 
that the tty is a bad terminal.
That reminds me. Gotta try something. Night.

* 2022-02-11 9:45 pm
I feel mad and sad. I have the pressure of doing that paperwork looming over 
me. I sort of want to ignore it and move away. Just leave this community for a 
bit until it stops mattering. It think Gabe hates me. I know he doesn't, but I 
still resent him. He's probably right, and he's treating me fairly. I just 
don't have the context or time or patience to really get on the same page with 
him.
At the end of the day I guess this isn't about him really. It's about me 
accepting where I am in life and what I must do. And I'm just not there. I want 
to ignore it and go on with the perks without losing that status as a kid.
The System is a big problem, and most of my vexations are caused by it. It's 
not my fault. In a better world I would have no conflict.
But in a worse world I would say that about this one. So let's just say this is 
the better possibility.
Boom. Depression destroyed with facts and logic. But obviously that's not 
sufficient. Need more.
The depression must have seeped in today. It really wasn't this bad. Let me go 
to the apparent source to alleviate this.

* 2022-02-11 11:06 pm
Well I filled out the documents and am feeling a bit better. Just called Mom to 
ask about printing and she didn't pick up. So huh. Also it looks like I made 
the elite council of Retreat Helpers-- which also includes Murray-sensei. No. 
He no longer teaches, nor am I his student. Murray-sama then.
Only one more hurdle: Safe Environment. From what I've heard, it's just a 
reactionary BS wrapper around somewhat-unknown common sense. I need to stop 
holding myself in such a paradoxical regard.

* 2022-02-12 10:25 pm
Nothing to say?
Emacs was taking several seconds to start. This was unacceptable so I deleted 
the original config. This new one uses a better packaging system, avoids 
lambdas and recursion, prefers native features where practical, and echoes its 
startup time in the messages area. It's now sitting below half a second so I'm 
pretty satisfied.
My eye is like dying. It's fine, but it's really not. I'm typing this blind and 
hoping it comes out okay. Editing it later of course. Surprisingly good...
Alright. Time to not sleep. Just had a dew for some reason.

* 2022-02-13 9:44 pm
It went smoothly. Office Depot to print the forms, retreat meeting, -etc- there 
was nothing else. Came home and did nothing. Tried to reinstall fedora from 
within itself to fix the dns issue, but couldn't get a mirror configured. 
Booted from live, chrooted in, installed stuff, ended up locked out of the 
system. Broken Pam and everything. Reinstalled again. It hurts. But now 
everything except tiling and emacs all-the-icons-font seems to work... Gotta 
enable that declaration. And set up silencing compiler errors for the 
native-comp pure GTK branch. I'm actually pretty excited, but I'm wearing pants 
to bed so it's hard to relax. But I have to so I will. Good night.
Best thing: I don't know. The hair. Let's say the hair. 
Hey, let's write that installation script!

* 2022-02-14 10:09 pm
Best thing: new daily exercise. Walking up to top of stairs, then to basement, 
then back to apt. Simple. Easy enough. Yet still consumes a fair amount of 
energy.
Also. Playing with emacs launcher window. I'd like to have it bound to s-e and 
open a fuzzy-finding file picker that then opens a new emacs frame and closes 
the current one. Or maybe put it on the bottom of the screen and leave it 
there. Call it a desktop panel or something. Like exwm but not bad. Also, we 
can create new frames but not disable windows. For some reason. Redefining the 
function leads to insanity. I don't understand enough to solve it yet. Hey 
let's put that on top and put the modeline on the bottom. Can that happen? Will 
investigate tomorrow. I'm not quite tired but I should sleep.

* 2022-02-15 10:18 pm
Best thing: went and bought TV stand. What I ended up with is janky, but at 
least it exists.
Emacs modeline as external frame is totally a thing, but it's kind of bad. The 
highlight groups don't really transfer over, and it needs to pretend to be 
focused. There's some work to be done.

2022-02-16 10:07 pm
Tired. But not really, just bored. Spent a while fixing my zplug config because 
the environment variables got messed up in converting to Org-mode. Well, it's 
fixed now. Painfully. I gotta fix the rest of the emacs configuration. Line 
numbers in Org and all that. Maybe get back the scrollbar and skinny font. 
Still haven't tried updating to pure-GTK properly yet. But hey, Mushoku Tensei 
s2 is downloading so I can watch that tomorrow.
Best thing: fixed zplug, and got strike through in Org-mode. It's plus signs, 
for future reference.

* 2022-02-18 0:11 am
Counting this as last night. Best thing: did laundry and showered. Ate la 
Cabana leftovers. Watched Mushoku Tensei part 2. This is gonna be a long one. 
Of course we have to wait...
Give me a minute. This show has prodded me. Our boy caved. It was her idea, at 
her insistence, and felt inevitable. But wrong. She was in a dark place and 
using him. She was in no place to consent. Consent? Fake. Need to redefine. 
Anyway. He rejected at first but wasn't thinking right. I was screaming at him, 
"this is not your arc" etc. And it wasn't. And she left in the night and 
unknowingly destroyed him. The guy's fragile. His default addiction is 
crippling despair, and she just leaves him there without so much as a goodbye. 
Just a note "we're not compatible rn bye". Yeah, they weren't. She couldn't 
understand him at all. Well how could she know? Huh. She put too much on him, 
and resented that. All in her head. Again, not capable of consent.
Here's my thoughts on consent: everybody's mental state is greatly influenced 
by their recent experience and past growth environments. Basically, what you 
look at as a mind is a tiny kernel of decision, some low-level but very 
abstracted drivers for behavior loops, an aggregate database of the past's 
highlights, and a huge storm of noise and junk knocking it all over. Most of 
the things anyone does, they don't think about or even know about. It's 
autopilot. Feedback loops and behavior drivers. When you knock someone out of 
their loop things get weird. They immediately take ownership of their actions 
up to this point _that they remember_, recontextualize these according to their 
current model of behavior, and pretend to be contiguous with their autopilot 
mode.
Enter mortal events. Like mortal sins but without the religious aspect. 
Basically anything involving addiction, sex, or other artificial alteration of 
brain chemistry. After the mortal event, you re-frame everything before it as a 
lead-up and everything after as the fallout, the sequel. The event is added to 
the highlights database.
Autopilot is resumed, but the patterns are different. The mortal event has 
introduced a trigger, a hook: things related to it will catch your eye. In 
extreme cases, a complex may be developed around it. This is how I feel about 
sexuality in general and innuendo in particular. It pisses me off for the sole 
reason (not the only, but a major) that I was once blind to it and consider its 
existence a betrayal of my innocence.

* 2022-02-18 11:35 pm
Didn't go to retreat. Gonna relax and stew here. Hate hate hate. Love it and 
hate the taste. Maybe buy a flip phone and hack it. You can get Busybox, so 
emacs can't be that far off.
Best thing: driving to McDonald's in the morning. Wonderful. I want to drive 
more tomorrow. But like, money. And food. Etc.
Got through a few episodes of attack on Titan. Up to the first twist. I think I 
hate all the characters. Mikasa least maybe. And that Sir Patrick Stewart 
general is pretty cool too. He better die a noble death.
I think I don't care for action. It's always the weakest part of the episode. 
Even when you are Mushoku Tensei and blew your whole budget on some sexualized 
bread tearing. Everybody raves about the amazing bread animation. But it's an 
awkward shot, and the movement is unnatural. Could have been way better with 
more shadow maybe, to draw out distinct shapes. Now I'm ranting about the bread 
too.

* 2022-02-19 sometime morning? 
I don't believe it's better. Watch you go. I go, I go, look how I go. Ikuzo.
They didn't call. Didn't question me. That means they didn't need me. Oh well. 
Cool then.
Don't count on me! Don't put your blame on me.
Couldn't find the phone I was looking for. Target was out, Fred Meyer only had 
the ATT version. Not ordering online because reasons. It looks like a good day 
out there.
Where's my Android lisp ide?

* 2022-02-21 3:05 pm
Had no night last night. Drove to Eagle River for no reason, got a snack, came 
back. Best thing of Saturday: not finding phone. Sunday: taking out garbage. 
Today: TBD. If I don't say later, put waking up.

* 2022-02-21 9:36 pm
Wow. Attack on Titan is crazy. Those first few episodes were still a drag and I 
don't regret dropping it. But there's enough mystery expansion to sort of make 
it watchable and interesting for me.
My head hurts. I was up really late last night. Had way too much caffeine and 
salt today. Actually no caffeine. Maybe that's why. It hurts. I will try to 
sleep.

* 2022-02-22 9:44 pm
Head hurt all day today. Had a piece of underripe pineapple for lunch.
Best thing: this moment right now. My head is finally clear. My nose is 
evacuated. It's all better.
I was really mad today. At least, I said I was. I set up all those meetings for 
yesterday and Josh blew them away like it was nothing. Told everybody the 
office was closed. The nerve! I will rage at him. I will complain. I get there 
every morning! I keep Jon company and listen to his ravings. I put up with 
Gene's annoyances. I call and apologize for him missing his appointments. And 
for what? For him to just throw it away. Well no. I won't have this. I don't 
mind getting paid for no effort that amounts to something, but if you dare make 
me try, it had better mean something! That's stupid. Stop lying and saying 
you'll be here before lunch. Stop pushing back all these meetings.
But I kind of don't care. Right now. And in the moment I wasn't fully sincere. 
I was disappointed and a little surprised and felt indulgent, so I said I was 
angry. And in saying, validated that anger.
Good night.

* 2022-02-25 10:57 pm
Best thing of 2/23: telling Josh I was upset. He said I'll "just have to get 
used to it". Ass.
Best thing of 2/24: Mac n cheese I guess. Nothing notable enough had happened.
Best thing of today 2/25: finally got something to install on the chonktab. I 
think I'll recreate my old configuration.
The Chris Chan legend fascinates me. I could have been him. In his time, with 
his influences. Not a huge jump. But I was more focused, and scrupulous, and 
nobody bothered abandoning me. So I stumble through my role in society in quiet 
and accepting rage.
I was always told to evaluate people without taking race or societal 
stereotypes into account. This made sense and was unanimously told to me, so I 
presumed it an obvious and ubiquitous truth. I heard of efforts to end racism 
and thought it was good to have already sorted that out. I saw Obama and heard 
that he was bad, and when asked was given some mumbling about taxes and wealth 
distribution and foreign policy. I believed this and thought little of it. Only 
that, it was a shame that the first black president turned out to be a bad one. 
I saw some random black people and they didn't seem to fit in. I gave them the 
same welcoming indifference as I would anyone else. Note here about gender 
inequality. Whatever. Anyway. I heard Trump and was relieved to hear such a 
blunt and based take. I heard slander that he hated Mexicans and kept listening 
to determine the truth. I was told that he merely hated the destructive ones 
who sought to enter America. I did not pursue this any further. I overheard 
that the right were racist. This confused me, as I was on the right and knew no 
racists. I mentioned at school that this was a pointless fight as racism is 
dead. Angel told me it wasn't. She elaborated that there were racists to the 
South, in the L48 and sub Panama. I accepted this, shaken at my lacking of 
critical information. This would be the first but not the last of her bursting 
my bubble. I still hold that Trump is not a racist, but acknowledge that his 
words have attracted and emboldened racists. This upsets me because I like 
Trump. 
I want race acceleration. My thinking is, racial traits in humans are just 
small scale evolutionary optimization. The blacks are black because it protects 
them from sunburn and skin cancer. They are prone to sickle cell because it 
protects them from malaria. Likewise the whites are white because they need to 
take in more vitamin D from sunlight. And likewise most every "racial" 
distinguishing trait is a simple and inevitable artifact of their amcestors' 
environment and should be treated as such. Some of these traits, perhaps most, 
are desirable for all humanity to have in the future. Thus, where possible, we 
should... You know...
I've always had that dream of a white blond wife and white kids and being a 
white old grandpa with white hair and a white beard and a white photo of my 
white dead wife and parents. Unlike ChrisChan, my delusion of a fated bride 
never dared reach that far with specifics. But it was implicit in all my 
thinking. In preschool there was a girl Ruthie Taygan. I hope I spelled that 
wrong. We promised to marry from across the leg of a small tallish table. It 
was preschool so everything was tall. I can't remember her face and wouldn't 
recall it from a photo of the time. I don't remember who started or proposed 
it, but it went something like:
"hey, will you marry me when we grow up?"
"sure why not"
"OK thanks"
"is this okay to commit to so early?"
"nah but it's probably fine"
This is translated, of course. From barely learned simple English. Though I 
have no memory of her being inferior to me. Not like No Clue Kid. I may have 
told his vignette already. I purposefully threw an accidentally-hard snowball 
at him, and successfully coincidentally made him bleed. He was crying and I was 
confused and felt betrayed by the stereotype of the innocent harmless snowball 
fight.
What else did I learn in that preschool? What a wart is. Teacher-san called it 
a wart and I misheard. I referred to it as a bumbp. I came home and my parents 
asked me what it was and that's what I told them. The next day I went back and 
told the teacher it wasn't a wart, it was a bumbp.
I lost a tooth. It was hanging by a thread, as baby teeth do, and I bit into a 
fruit leather. It was the green apple kind. I bit fine and got it halfway into 
my mouth but it felt weird so I took it out and the tooth was stuck in it. It 
was one of the big upper front teeth. I think. Maybe a canine.
I think I sat out a game of tag. This was to become a pattern. I hated tag till 
I was old enough that it never came up.
Learned of the pupil of the eye. I think I was told of that before and this was 
a reminder. I knew that pupil meant student and did some wordplay with the 
teacher that confused both of us. She explained the other meaning to everyone 
else.
Might revisit the preschool memories later. This is all I'm recalling for now.

* 2022-02-26 4:23 pm
Charlie says he'll come with Lill and her sister's truck and his couch. At 
7:20ish. We'll see how that goes. I'd maybe clean up but up to a point it 
doesn't matter. I want to appear together but not totally hygienic. It's a 
better plot than strapping it to the car...

* 2022-02-26 11:05 pm
Went fine. They came over, Lillian stayed in the truck, Charlie and I made 2 
trips.
Best thing:  finally recorded YouTube video. Latest since 4 months. Gomenasorry 
about the shallow take.

* 2022-02-26 11:17 pm
Bad take bad take: suicide.
I'm not suicidal. But when I was (or was close), I was acutely aware that the 
"suicide hotlines" etc were dumb. How can someone on the other side of the 
world understand at all? And how do you expect a person in such a state to ever 
call? Please correct me if I'm missing critical information here. I'm just 
enraged that such a stupid institution would exist.
Bad take bad take: passive ethical eugenics.
They're banning anti-vaxxers on discord right now. But why? It would be so much 
more efficient to just let them carry on, then they and their children die and 
the whole future sees the fruits of their idiocy. This overuse of the ban 
hammer is not merely authoritarian, it is moronic.
The inverse should be said of the generally weak. If someone cannot naturally 
function in society nor bootstrap themselves despite an issue, letting them 
produce offspring is reckless. Sure it's nice and we feel good about empowering 
the helpless. But in the grand scheme, it makes no sense. By passing down a 
defect, you are cursing all of future humanity with it (since after a few 
hundred years the gene pool is remixed). Now, since some extremely positive 
traits are tied to extremely negative ones (cosnmically preserving the balance 
of each human). In these cases let time tell whether this trade off is worth 
it. If they succeed by coincidence, cool. If they fail inevitably, oh well. We 
shall passively await a better version of the trait to pop up. And passively 
allow them to win in life. This may sound shallow because I am reducing 
personal growth to successful reproduction and the individual to a data point. 
But am I wrong?
I do not know if bad sight is genetic. But if it is, then glasses are hugely 
evil an invention. They have created complacency. People are enabled to be 
parents despite a cripplingly undesirable trait.
Sex is not the only success. Contributing to the understanding of humanity is 
also a success. And if someone with bad sight, or broken reproductive organs, 
etc accomplishes this, they should be revered for their accomplishments above 
those who merely fuck and live on. But it is better for one to both accomplish 
great advancement _and_ fuck.
I'm falling asleep.

* 2022-02-27 8:47 pm
Best thing: working on fixing emacs relative line numbers. It's kind of stupid 
how this isn't yet a thing.
Basically, in vim you have a couple options. `set number` turns on absolute 
line numbers on the left. Emacs has always done this in multiple ways and that 
is no problem. Vim `set relativenumber` displays each line number as the 
absolute value of the distance from the current line, with the current line as 
0. Emacs can do this also in a couple ways. But vim has an awesome behavior 
when you combine the 2 (`set number relativenumber`): it displays the 
non-current numbers as in relative to current, but the current line's absolute 
number from the top, with the current number left justified so as to pop out 
from the relative numbers. Emacs has no notion of this so I spent several hours 
attempting to build it from scratch. Haven't succeeded yet and there are still 
some major issues. But it's probably possible.
My head is spinning with the absurdity of Chris Chan. The grammatical dialect, 
the interweaving yet contradictory delusions, the nave self-righteousness, 
the pointless retcons. And of course the influence of the trolls.

* 2022-02-28 7:36 am
I had a dream. I was working for Walmart against the thieves and my job was to 
hide in a couch near the front wall that they sat on. I spoke from behind them 
and said something nonsense about silverfish and Minnesota, then gave them a 
warning that at 2 in the morning they would be arrested. It was 10 pm. I then 
went out to my car and stood next to the door. My accomplice, an overweight egg 
head type girl, came out. I sort of weakly yelled to her are we supposed to 
stay here, but she didn't hear me enough to respond. I saw some cops and it was 
weird because we were in cahoots but I didn't trust them.

* 2022-02-28 8:22 pm
On hanime I saw a comment: "I would switch to this school in a heartbeat". The 
school in question has a ritual in which the three highest scoring boys at 
tennis each pick a girl to do sexual things with. I had accepted the premise 
and found it hot provided the twist that the MC was shy and the girl he liked 
chose him instead. But that comment broke me out of it. How could you _want_ 
such unequal degeneracy? And yet, I am afraid that if I were in that school I 
would make my peace with it, and even play the tennis and be in the room, and 
would speak out against the ritual but secretly get good so as to be forced to 
participate in the degeneracy.

* 2022-02-28 9:33 pm
Best thing of today: writing schedule.ps1 script. Hopefully John will bring 
over his copy of Visual Studio so I can bundle the pdf parser dependencies. For 
now it just pops open all the court pdfs, which is nice but kind of a strain on 
the computer. Parsing the pdfs themselves would be much better. Also we gotta 
see about spam-opening court view. Parsing shouldn't be so much a problem cause 
that's all html and hasn't been updated in 10 years. It's the redundant 
database queries that get me.
Windows scripting is strange, annoying, but refreshing experience. A lot of 
looking up simple things because their manpager is garbage, but complex filters 
just work without weird sed nonsense. Which is really nice. I'm not convinced 
that visual studio will be worth it. The it being free with a shallow learning 
curve. It's Microsoft garbage so I'm skeptical, but if it works and is portable 
I can't complain. Also had to rewrite the script from memory today due to a 
botched copy/move operation. Stupid powershell coreutils...

* 2022-03-01 7:22 am
Had a dream. Setting was like Attack on Titan but without the walls or odm gear 
or anything. The however-many of us were at the park when we realized what had 
happened, that everyone not present was a deadly monster. My father was locked 
in our dungeon for maternal incest. Me (or at least who I was looking through 
the eyes of) had 3 siblings. A badass and stoic older brother, a badass and 
chill older sister, and a sweet and cute younger sister. After we learned of 
Dad's actions, the younger sister and I began to fondle and fuck every night. 
The older 2 came back from an expedition and sat on the wall bench opposite us. 
Older brother began to sleep, out cold. Older sister was giving me ambiguous 
eyes (I can't remember what led me to the following action). I kissed younger 
sister and she fell asleep instantly. I looked up at older sister and she said 
"how did you know" and we made out.
Also somewhere in this same night's dream. There was a battle with a Titan near 
a small cliff and a bendy tree. A guy got swallowed and we threw him some gold 
to make the Titan throw him up. It didn't work, but thankfully the Titan did 
have a digestive tract so he came out the other side with the big chunk of gold 
and hightailed it away. The guy trying to rescue him had been using the bendy 
tree as a spring and ladder and jumping aid.

* 2022-03-01 8:27 pm
Today. Was a day. Went to la Cabana for fat Tuesday. Guess I'd better fast on 
something slow.
Now I remember the worst thing about the existence of sex. It is this: the 
assumption that guys want it, that this is a primary and insatiable desire for 
us, and that we are thus an inevitable danger to women and children. I believe 
in children and teenagers. I have seen firsthand the hope and passion and depth 
of experience. But I am 18. Almost 19. And that makes me a Young Adult. Which 
makes me unable to... I'm getting the internal embarrassment that this is all 
in my head and if I just tried it would be fine. But I'll rage some more here 
anyway. It makes me unable to interact in a casual and friendly way with anyone 
younger and/or of opposite gender. If I talk to a guy within one year or 2 
below me that's fine. Any more and I'm a disgusting gay pedo pervert. If I talk 
to a girl under 18, I'm grooming them to want sex when they "grow up". This 
can't be a wholly inaccurate view of the world, right? So. I wish I were like 
60. Guys who are 60 and have long flowing beards and a public position and 
hedge funds that leak into the public benefit and have written a book or 2 that 
none of their friends would read because it's too specific but it would really 
be a good read for anyone: those kind of guy is what I want to be. An eccentric 
and smart, yet wholesome, everyone's favorite uncle type guy. If neither myself 
nor society will let me be an _ore_, at least let my _watashi_ not ring hollow.
Man, I just realized something. This document is going to be very cringe when I 
read it back next year. I'm going to do all kinds of things to it and it's 
going on my website. But I'm thinking I should get a therapist and tell them 
all about this. And show them the document. I bet they would upcharge me. Aye, 
that would cost money and money is something I don't feel like spending. It's 
fine, of course: I have loads of extra money.
Should I quit this and go to college? I could maybe still get into Thomas More. 
I'd study theology/psychology, then go into law. I could be a lawyer like Josh 
but not drinking. Can't be harder than being Jon right now... He's made the 
best of a messy start up till now. Josh had a great start and that's a crutch 
for him. Gene needs left no start, for he is past his end. And I... I have not 
yet started.
I need to not wish to be a different age. Such brings only pain, regret, and 
pre-gret. Maybe it'll be better then. But if so, the least I can do is cope now 
in a way to set up my then to be better.
That dream last night was f'd up. I should not have had it. But I did, so may 
as well say it. Here's to a better one tonight.
Best thing of today: working more on powershell script that opens all calendar 
pages. Now it skips the ones we'd never want. Need John to bring in the visual 
studio cd to bundle the pdf dependencies. Hang on. I used this yesterday. He 
forgot to bring the disc in.
Actual best thing of today: writing in here. I've brought myself down.

* 2022-03-02 9:19 pm
Best thing: emacs load-path. It was frustrating but I finally got it in there. 
Always put (provide 'thing) in the file to be loaded and (require 'thing) 
before where it needs to be loaded. Nothing I read said that directly, so the 
realization came like a stupid and blinding suspicion.
I want to write a new lisp in zsh. Just saw a post about a guy writing a scheme 
in python and he gave some good tips:
- there are 3 parts of an interpreter:
  1. Parser
  2. Translator
  3. Evaluator
He then demonstrated how a lisp style list structure looks in python, and blew 
my mind. Also lisp is a tree structure, a data format and an executable string. 
The best of json and xml and ini, and the deepest of subatitutive programming.
I want to write all that emacs has from scratch, to understand it. I don't 
right now, and I doubt anyone fully does. There's a nano clone written fully in 
guile. I might try that.

* 2022-03-03 9:20 pm
Best thing: decided to give up YouTube and spider solitaire. I've been wasting 
my time on them and need to stop.

* 2022-03-04 7:18 am
Friday... Without youtu.be. Without solitaire. How will I do?

* 2022-03-04 10:20 pm
Best thing of today: I'll sleep in a moment. That shall be the best.
But first. I need to say a few things.
I am perplexed by the character Josh. He's oldish and has his life together, 
yet he's always late for things. He makes excuses like a 16 year old who's 
smart enough to make them true and lazy enough to keep them coming. He drinks 
all the time, yet his work consists of every allegorical instance to reject 
impairment. He has no sense of his car, or appliances. He buys food and lets it 
rot in the fridge. Now he's supposedly giving up alcohol for lent. I don't know 
whether to be afraid or overjoyed. Certainly not overjoyed. Mildly impressed? 
Still. Too little too late? The guy is stringing us along. At least I'm getting 
money from it. I should find a new job. But this is so chill... No it's not, no 
its not. I have no life left. No time to do other things. The weekend is a 
curse that makes me decompress so I am softened under Monday's harsh blows.

* 2022-03-06 2:42 am
Counting this as yesterday. Best thing: installing windows 10 virtual machine 
for visual studio. Now I'm having to write visual basic and it's confusing.
After all... To end... I'm so tired.

* 2022-03-06 5:33 pm
My wifi Hotspot broke this morning. I'm not sure what happened, but it appears 
to be an internal dns issue. Switching connection managers or even using an 
android doesn't appear to help, though.
I'm so fat. I've eaten so much, and cared so little. I used up all the eggs 
today. Have to buy more plus milk tomorrow. I'll eat that milk as cheeto Mac 
and finish that as well. Tomorrow will be bad. I'm not in a good place mentally 
and Josh will probably be in early. Which means more hassles. Less than a week 
into Lent and I've already broken it all.

* 2022-03-06 6:08 pm
Hmmm. Not a ton to say. It's been 3 months into the year 2022. That's a 
quarter. Nah, it's really more 2 months. That's 1/6. Less impressive. Well, 
soon I'll be 19. A whole year of adulthood. A whole wasted worthless year of 
filler. Nay, quite the opposite. I wrapped up a lot of arcs and began lots of 
new ones. The high school meta is out now, the cut-cast office sitcom drama 
slice-of-life survival guide is in. I've said before in here that this is the 
worst time of my life. I said that for reasons: I'm old. Too old to be a high 
schooler anymore. I understand ChrisChan in how he felt on losing high school. 
They dump you with nothing. Then again, I'm more troubled than Chris, and thus 
more useful and self-conscious. So my life isn't over. I don't have the support 
network for it to be over. I'd honestly like to ditch this job and just live as 
a landwhale in some benevolent basement, but I don't see one around. Not where 
I could hide from those who wish the best for me. Just let me screw myself 
over! Ay, my life like this is revenge. A passive and fruitless internal 
vendetta against the voices without. Dad, telling me to stop hiding and do 
something. Mom, nagging me to avoid "sin" and making bad-faith arguments. Gene, 
thanking me for nothing and saying mom is proud of me. But what of the rest in 
my life? What of Charles? What of Lillian? She is no longer in my life. We have 
no excuse to interact, and I am ashamed. Ashamed to presume I could sympathize, 
empathize, with a woman. Especially one with so much pain within and without. 
My life is a cake walk compared to hers. Or so it seemed last I bothered 
reflecting. When I left Dad's home. I called her. I had thought I was in a bad 
place, but it was her. I was fine. I didn't realize on the call, of course. I 
wanted to live on her property. I wanted to flirt. I wanted to "help". To help. 
By listening, and learning, and saying the right things. Did I want that for 
her sake? I know I wanted it for mine. I wanted a de facto mate. Just like 
ChrisChan. I wanted to have her. I wanted her to be mine. And together we would 
discuss and discover what it meant to be woman, or man. She would help me out 
of my shell, and I would step her out of hers. Truly, my fantasy reached up to 
the heavens. And we would be good and true Catholics working to conquer our 
vices.
But no.
She had already latched onto Charles. I can't wrest her away. And I shouldn't. 
I'm childish. I am a silly little boku wa baka.
When I called her as I ran, I had been watching re:zero. And Subaru, Our Guy, 
is like Charles. I identified with him and thought I could be "that person". 
Whatever. My passions are calling. Time to watch the last half of the first 
half of the last season of attack on Titan, a show I dropped after episode 4.

* 2022-03-06 8:48 pm
Best thing of today: the ice cream. Birthday cake flavor. It is truly the 
nectar of the gods. I certainly didn't do anything to be proud of...

* 2022-03-07 9:44 pm
Best thing of today: shredding. So chill.
I broke professionalism today. Daron called and begged for money. He said he 
was lucky he had a heart attack yesterday so he didn't freeze overnight. I told 
him why don't you do it again. I told John in an apologetic manner and he was a 
little disappointed but understood. He said he wouldn't fire me for something 
he would have done himself. I hope they lock that loser up.
It's a strange thing: Daron is a loser. Josh and I are winners. What's the 
difference? How does Josh win? Must be circumstances and quick talking. 
Everyone who wins has some merit and some luck to it. Take John. He was born 
into a network of infamy and fame, where everyone is a crazy rich loser, and he 
was taught to maximize capital at an early age. This was his luck. But he ran, 
and struck out, and learned, and made himself useful. This was his skill. The 
thorn is his failing body, and his kindness toward losers. Kevin is a loser. 
Yet John cannot shake Kevin, for he has hope. He denies it, but he does. He 
says he'll buy Kevin an apartment, pay the first few months, and kick him out. 
But that will not happen. Kevin couldn't keep a job if he wanted to, and he 
doesn't want to. John cannot comprehend this and keeps giving him more chances. 
And what can he do? His only remaining course of action is to continue on the 
current trajectory: support the loser, but complain about it. This is John's 
vent: the Complain.
I'll try again. I want to use Windows on the chonktab. But no drivers will 
present themselves, etc. So I will have to use a thin Linux as the host. I want 
it small and declarative if possible. A nixos? Nay, a guix. Because lisp. I'll 
write an os loader for windows in lisp, and slap it on github. Throw it out on 
r/Linux too maybe. Worst that happens is I get banned from reddit. Which I 
haven't used in months. Best is I get fame as "the guy who solved windows 
drivers forever".

* 2022-03-08 7:21 am
No reddit and no YouTube. My brain wants stimulation right now. But I have none 
to give it. I have to look at reality, at the silly waste of my organization of 
this apartment. I should really reach out and ask for a studio when one becomes 
available. It'll be a money sink initially, but will save tons in the long run. 
But I'm nervous. I feel inferior. I brought the scourge of bedbugs upon this 
place, and I'd hate to make it any worse. Or to look like I wanted to or didn't 
care. I want to look like one who cares immensely. Who goes his own way but his 
way is right. Is that possible? Is that worth anything? It's insincere at the 
very least. I don't mind the bedbugs. We have reached an acceptable stalemate, 
and in my judgment further squabbles will accomplish nothing. But in the eyes 
of the world, this is complacency. They will not let them an inch, for they 
take the mile. And yet, they take their own inch too. They are a force of 
nature, like the rays of the sun. To truly eradicate them would be to slaughter 
all of humanity. Which if you care enough would be an acceptable solution to 
me. But I doubt that those who presume to hate bedbugs would dare go that far.

* 2022-03-08 8:50 pm
Bad. Bad bad bad. What do we idly wish for, and where do our dark daydreams 
destinate? Mom is breaking down. Her mind has begun to crumble, and she isn't 
aware enough to keep up. Let alone limit herself to conserve thought. Now she's 
texting again with "hope you enjoyed your day". I'm worried. I'm hella worried. 
What happens when she goes vegetative? Well, I'll go there on Saturday to see 
how bad it is. She was sort of okay before. Oh. I gotta talk to Gene. ask him 
if he's noticed anything like this. He might know who to call too. I need to 
get her a doctor or something.
This is stupid. She's not old yet. She's not even 60. She has many more years 
to live out in obscure and competent peace.
I've wished her to die. I've fantasized about her funeral. I would be quiet, 
stoic, somber. To the outside it would look like her death brought me back to 
church. Which it would. But really it would be a pure convenience. I don't want 
to go to church with her or without her when she's there. I can't make her 
leave. So her dying is the perfect resolution for my comfort zone. Such 
convenience. I've outgrown her, after all.
But that fantasy is falling apart. Now that she is going in the most horrifying 
way possible. I mean, I'd be terrified to go that way. But I treasure my mind. 
She took hers for granted, and I suspect this has been going on for a while.
All those years ago. I didn't grow out of her, she began to collapse and I 
didn't notice. Dad didn't notice. We were too caught up in our own changes to 
think anything of it. And we lost her.
I need to call Dad and keep him in the loop.

* 2022-03-09 6:57 am
Woke up early this morning. Too much dew. Now I shall play on the computer, 
striving for the ideal state.
I will wait on telling dad. No, I can't wait. But I will. Ehh. I can't tell him 
but I can't not.

* 2022-03-09 9:58 pm
In a few hours I will count as 19 on the public record. It doesn't mean much 
but I can inject whatever meaning I want and have it stick. This is a chance, 
not to be wasted on cheap disappointment.
How about: each week I will learn a new Japanese character. If not quicker. I 
will spend a comfortable time to deeply understand what it is and how it 
behaves in context. It will be the subject of my daydreaming.
Alright. Cool. Anyway... On to normal business.
Best thing of today: schedule script is coming together. The sh part is 
trivial, the Python part must not be touched, and the pwsh part is pretty well 
refined. I want to add a simple markdown or tex template and have it generate a 
docx or some such. In the same format as Jon's hand-written word files now. 
It's so close. And then I'll slowly convert the whole project to PowerShell, 
and then make it bootstrap its own dependencies, and then ship that as an exe.

* 2022-03-10 7:22 am
It's time. It's good morning. I am awake and I am 19. I've lost too much to 
time, I shan't lose this too.
I had a dream last night. I was a skeleton like Ains Ooal Gown and was trapped 
dormant in a cave of some kind. Also there was Emilia from re:zero on a dog 
sled traveling north in the Glenn highway right before Butte exit. But the exit 
wasn't there and the road was closer to the mountains. She was right behind 
several huge semi trucks. They all suddenly peeled off the road and she flew 
very fast toward Palmer. I was still in the cave, standing perfectly still. I 
had been discovered many times throughout the centuries, but never given any 
food.

* 2022-03-10 9:17 pm
Best thing of today: converting the schedule script to (mostly) powershell. I 
still need to figure out grep though. The current thing just passes everything 
through. Maybe because powershell pipes work on objects and not true streams? 
Filter left, they say.
My day was okay. Woke up feeling pretty good in the morning. Then John drones 
on for a while, but eventually left me alone. La Cabana was fine, but I ate too 
much. Afternoon was kinda miserable with the digestion and filing. That copying 
at the end killed my mood and I had to get out of there. Then the rendezvous 
with Julie was mercifully short and I got to relax for an hour. Mom and Clarice 
kept calling me, which was annoying. But mom dropped off some candy so that was 
nice. Though she did slip some plain old sugar packets in there. Come on.
I need to stop being a pushover. I should be more rude. Or at least reject a 
fair percentage of optionals off hand. Man. I couldn't get a good break today. 
I hate that. Just leave me alone. Let me hide. Let me brood. Let me think. Let 
me breathe and hack. If I can't get friends, I don't want sympathy from 
acquaintances. I'm mentally deranged, and maybe even an introvert. Leave me 
alone. I'll come out when I need company. I know you'll be there. Somebody will 
be there. They can't not.
In the apartment there is peace. In the car there is peace. In the empty 
office, or without the boss, there is a sort of peace. In my room as a child 
there was peace. On the computer there is peace. On the toilet is peace. In bed 
is the best peace of all.
Leave me alone. Why must you drag me out to suffer and gain? Leave me alone. 
How do you not understand this very basic human need? Leave me alone. 
Everything will go my way in life, except for you constantly bothering me. 
Leave me the hell alone. I don't care about your stupid cargo cult. Leave me 
the fuck alone. I would be okay with solitary prison. Just leave me alone. 
After all, this is very much a prison of sorts.
Hmm. Does this... No. I can't. Can't think. I am tired and sugarbuzzed and I 
suspect tomorrow will be horrible. But with a single lie I could take it back. 
Just say mom poisoned me by accident, and I need to get it out of my system. 
That would be simple and easy and effective. But alas. I don't like lying. Too 
much liability. Haha pun. Bad pun. Has sound without meaning. I should write a 
thing on what makes a good pun good.
But now. Sleep.

* 2022-03-11 6:57 pm
I know. I feel. I see. I breathe. I itch. I scratch it. And I always fall, a 
little short in front of you.
Ani-cli works on Android now. That's pretty cool. Not as cool as having a whole 
local streaming setup, but okay enough.
I was vulnerable today. I told Jon about Mom. I guess I'm kind of bound to do 
something about it now. And I hate that. I wish she'd just die. Leave me alone. 
Pay for your annoyingness and leave me alone forever. Better occasional regret 
than constant pestering. And I don't even believe in regret. Well, I have 1 
regret. One singular little regret. And it will not change till I lose the 
faculty itself. For I hate... Nah. Leave it be. See, this is the problem. In my 
sane moments, I hate it. I would cut my penis off if that were an okay thing to 
do. Obviously it isn't so I don't. But when the mood strikes, I become 
protective, horny. What a horrible word. The etymology is presumably related to 
erection, but it doesn't mean erect. It is a mostly mental thing. That will 
then become physical arousal no matter what.

* 2022-03-11 11:40 pm
Best thing of today: reading re:zero. We got through the Darkest Moment and 
into some great lore teases.
The bedbug crew will come on Sunday, not tomorrow or today. A shame but oh 
well. I guess I'll lay about tomorrow and do real things Sunday.
Been re-adding the xfce config files to my dots repo. I want to use qtile as 
the window manager. It doesn't deal with xfdesktop well. I can see why I 
disabled it a year ago. But this time I'm going to make it right. I'll make it 
work with the default apps as intended. Every distro and desktop default will 
be usable in the same way. I've already done it for gnome and sway. Now if I 
can perfect xfce and make that the window manager... Wait. Why am I not 
leveraging the subarashii lisp WMs like rat poison, stump? There's so much 
potential there. It's lisp, after all. Okay. I'll do that. A major concern will 
be distro availability, though. We need a fallback. Xmonad bootstrap?

* 2022-03-12 7:37 pm
Best thing of today: getting out of mom and Clarice's presence. They're both so 
exhausting.
Qtile mostly works with xfce now. Just not xfdesktop. I am not sure how to 
handle that. Perhaps I should just switch to a more powerful WM. The Haskell 
dependencies for xmonad are just so troublesome.
So that Xbox controller. It doesn't work as a mouse, but it does work in games. 
I started a MC bedrock game.

* 2022-03-13 9:39 pm
I believe now that criticism of film or indeed any story can be valid and 
constructive. However, I do not think myself capable of such things. I do not 
notice, because I make everything explained through headcanon. I will believe 
anyone, accept any story beat, etc. As long as something does not disgust me I 
will come to love it.
Bought a MacBook today. A 2020 arm model. Why? Something to do. Something to 
hold when I lose my grip.
Best thing: sinking into this hot bed. It's so hot and nice. Okay.

* 2022-03-14 11:55 am
Aand as soon as I begin to write here life calls once more. I skipped the 
morning of work. Last night was awful. So hot and sweaty and bloated and 
accelerated. But I've had my slow wake today, so I'd better be okay.

* 2022-03-14 8:39 pm
And, to everyone's surprise, I was. Nothing happened, nothing was lost. I 
skipped the awful Monday morning, Jon had a slightly worse headache, nothing 
was lost. Man. Taco bell nacho fry burrito is the best. The pinnacle of both 
nacho fries and fry burritos. It's as if they were purposefully teasing this 
crossover from the beginning. And I am so here for it.
The m1 MacBook is awesome. The battery life alone is a living legend, mapping 
caps to esc was trivial, and homebrew for package management just werks. Mpv, 
alacritty, emacs, brave, my wallpapers, zsh-- it's just so smooth and 
refreshing. Even putting in my git credentials was a cinch. And the Amethyst 
window manager is literally a clone of xmonad with no effort required for 
config. Ssh works. File paths work. So many things work, it's almost hard to 
believe that Linux falls so short comparatively. I was going to have a huge run 
of revamping my config style to new default apps, but I don't need to because 
my own default apps just work.

* 2022-03-15 8:21 pm
Read some more re:zero today. My mind is blown and racing. Truly so much is 
just kind of happening right now. I can't wait for the end... But I need to 
sleep. Etc.
Best thing of today: KFC pot pie for lunch. That seems odd and disappointing. 
Oh well.
This goal of learning Japanese will not happen at the rate I had intended. It 
will be slower. Much slower. But I will come to comprehend it all. Eventually.

* 2022-03-16 9:09 pm
Re Zero continues to be subarashii desu. Best thing of today: sorting phone 
messages and starting on the rewrite of the Messages program. John gave me a 
copy of his version. It's a compiled exe but it's kind of garbage. Can't split 
text onto multiple lines. Won't add me to the drop down menu. Doesn't have a 
time or date override. Print dialog is janky. Whole thing is blurry. That's the 
thing, isn't it. The windows dialog is blurry. Huh. Well. I'm making a serious 
shot at it in powershell, and I'll write it such as to maximize hackability. 
Hopefully I can find an elegant shortcut to avoid copy-pasting all these 
properties. For loop? Hmm. Variables are different than in sh, so procedural 
variable generation may not be so simple. It's just a couple of drop down menus 
and a text field. Why do I care? I've seen the version where the author didn't 
care. I'm stuck with it for now. It's strange. Might be the first "bad 
software" I've ever used. And that's quite significant seeing as what happened 
in the distant past...
Nevertheless, I'm super excited. I got home and was mad I couldn't keep working 
on it. I almost tried AppleScript. Which I kind of don't want to do.
The IDE cult is perplexing to me. It's like in these newer languages you can 
barely just open a file, add some text, run it in the terminal. No. Open this 
huge editor, click the new project button, go through a list of templates, and 
it writes every step for you. Now with github copilot you don't even need to 
open a browser to copy other people's code. Let alone understand the language 
you're writing.
I want to understand. I want to build on that. I want to explain and exalt and 
lovingly dissect each and every thing. I want to be the Wizard that makes it 
all make sense, that translates between intention and result. Itself static, 
needing nothing in particular, but being a loved and firm ground upon whom they 
all may thankfully tread. These losers, they could be judged objectively by 
all, without the stupid system batting them around. And we could see for 
ourselves whether their complaints were valid and explanatory. This would be my 
heaven: to rip away all confusion and misunderstanding and pretense and 
ignorance and ambiguity etc. For only then can there be peace. Only then can 
there be acceptance. Only then can anyone really say what is wrong or right. To 
see. To actually comprehend, and not just half comprehend and ignore what is 
inconvenient and difficult. To be forced to understand. That is the greatest 
catharsis. The wonderful pain. Of seeing one's sinful past and truly knowing 
why and how it was sinful, having both the perspective of your former self, and 
of the Truth. That is what I want. To be able to say with absolute certainty, 
"I was wrong, and now I am not". This too is the essence of true humility. 
Nothing braggadocious, nothing self-flagellating, but merely the obvious fact 
of the matter, and all matters.
We are not there. And so I stumble along and continue to defend my current 
self, and to re-analyze my former self's actions and remarks. Why didn't I 
think of that? If the current me were in that situation, with that set of 
facts, I would have certainly been different. Yet I was not. I am changed. 
Changing. Imperfect. Relative. This mind is not enough for its ambitions, and 
the body is ill suited for either. I could get better, I could take better care 
of myself, but why? It won't bring me any closer to this goal! It's just time 
spent and discomfort brought upon oneself. Why go through any pain now when you 
could push it back for later as a regret, then have a purely healing pain after 
the Big Reveal? A mental, intellectual pain. The pain of living with yourself. 
This is what I worship, I guess. It is a rash value judgment to make, but it is 
a certain kind of an end. With sunk cost comes a self-cruel objective 
abandonment: I will continue to sink the cost, and it will become a waste. Then 
I will jump off of that endeavor, and the cost poured in to the previous will 
be lost. I had an old laptop. Its value was probably about $80 in today's money 
with the depreciation of such devices. Well I poured at least $350 more into 
that thing. I gave it a better screen. I gave it a better battery. I gave it an 
SSD and a bay and a hard drive and a wifi card with Bluetooth. It had been so 
dramatically extended. And that's with not a word to the software. I optimized 
everything, short of just using Gentoo. I crafted the whole thing around my 
use, and sunk countless hours and others' dollars into it.
And then I gave up on it.
I gave it to charity with a stock Mint install and bought a newer model. For 
around $300. It did most of the things, and almost all of them better.
But I digress.
And in doing so, I tire. How truly slothful. Taida desu ne.

* 2022-03-17 9:26 pm
A mostly good day, I suppose. Just fine, in fact. Best thing: 'clear' button on 
my message-taker powershell form. Eventually we will have also an email button 
that sends an email, and a print button that opens a print dialog from which to 
print. That would be great. First I will catch up to John's, which he claims to 
have slapped together in an hour.
Worst thing: I put a 2 instead of a 3. On a request to speak with an 
incarcerated potential client. So now we need to resend it or just forget. But 
that would be sad.
I got to use my ffmpeg knowledge again today. To cut another audio for a dmv 
hearing. But I'm not going to go to all the effort of making a transcript. The 
default IBM thingy is garbage and it costs money for better. I've already 
wasted the company's money on that fake scammy person-finding service. And I 
need to get that canceled soon... But I won't. Oh well. The spur of the moment 
led us to this, and it will loop back around to stick us in the back.
Good night?

* 2022-03-19 7:51 am
Forgot to come here last night. Was thinking way too much about emacs extension.
Best thing: hmm. Probably the night and working on my emacs manpager 
highlighting.

* 2022-03-19 11:42 pm
Best thing: wandering around Fred Meyer talking to myself. Looking for a square 
light bulb, which they did not have.

* 2022-03-20 10:47 am
Caught up on attack on Titan. Only a few weeks left to wait. 86 part 2 is 
supposedly finished, but I don't believe it. That show ended last year. 
Whatever. I'll watch it just to see it through... Now? Sure.

* 2022-03-20 8:22 pm
Set my alarm earlier. Might help for some reason. I really don't want to become 
grumpy and stiff like Jon. Well, whatever. Took a shower. Now the hair will be 
awful for a few days, then great for a couple of weeks, then get bad and 
require another shower. A miserable existence to be sure...
Best thing: cleaning toilet. It turns out you can push all the water through 
the system and clear it out to scrub or treat the bowl. So that's nice maybe. 
Also cooking rice was good. I like rice when it's with things I like... Hmm. 
Need to do something with the other stuff. More milk for the cheeto mac. More 
ramen packets. OK oh well.
I need to steel myself for another day week life of the office. To not get 
annoyed by Gene, or depressed by John, or fed up with Josh. Oh. Right. I have 
one mor more chore to do today... Bye.

* 2022-03-21 8:22 pm
I guess that went okayly. Okaily? Okaly? OKly? Nah, OK is already the adverb. 
Well what evveth.
I didn't particularly fail today, but it all came off as disappointed of me. 
The chili of LA Cabana is always too much and it gives me a headache. A food 
headache, representing Gluttony. As opposed to a stress headache, representing 
Sloth. Hang on. This is subarashii desu. Is there a different headache for each 
Deadly Sin?
Food headache: Gluttony
Stress headache: Sloth
Argument headache: Pride
Exasperated headache: Wrath
Greed?
Lust?
Envy? ~Jealousy, turning snakes into the sea.~
Oh well. A good metaphor, for another time.
Best thing: waking up at 7 this morning in advance of the alarm. I'll set it 
back 5 minutes now and see how much I can each day.

* 2022-03-22 8:49 pm
If I lose it all, then I lose it all. What a meme. Took me several episodes to 
get it. I was hearing Japanese so I couldn't make out the English. What a 
problem.
These past few days, there have been things I thought, "I should write this in 
the document" and then didn't. That's a thing I guess. Or rather, it is not.
I spoke with John about - - 

* 2022-03-22 9:38 pm
Fitshucks and shitfucks. Clarice called about mom and ruined my evening. I gave 
everyone everyone else's numbers so they can leave me out of it.
Best thing of today: If I Lose It All. Great meme.

* 2022-03-23 9:49 pm
Best thing: reinstalled server with Ubuntu Desktop Minimal instead of Debian. 
Just Werks, unlike the weird phantom wifi problems I had been having. Now I 
just need to make sure that the hotspot restarts itself on reboot. A venture 
for another time.
I can't get into this 'watching anime as it comes out' lifestyle. I've been 
sort of trying with attack on Titan since I caught all the way up, and the 
latest episode was just so much less impactful without that week long binge 
behind it.
Also... Programming stuff.
I'm trying to grasp the essence of powershell so as to actually use it well. 
Here's a breakdown:
- everything is an object, including strings. But the text on stdout is not 
itself, but an arbitrary presentation of its underlying structure
- objects are also shell variables like in sh, and evaluate to their content, 
and can be set similarly
- arithmetic is trivially simple including substitutions and parentheses
- pipes work like in sh but wherever possible work in objects and not simple 
strings. If you pipe into a legacy coreutil it will be treated as a raw string 
though.
- in addition to variables (nouns) and commands (verbs) there are operators 
like -ne or -replace which can change the result of the expression to a bool or 
modified string/variable object
- Quotes are the same as in sh, parentheses are as in lisp but mostly optional, 
the math is python math, the flags and switches are -single -dash like the Xorg 
tools, and the default verbs are ThisCase-Verbose ly long, as most are tapping 
into the Microsoft api.
Good night.

* 2022-03-24 9:46 pm
Today, for the record, I high centered my car on the berm by the road. I was 
trying to slow down so as to not rear-end the rando in front of me. I veered 
into the side, then right over it, and found myself unable to move. I poked 
around with ice chunks for 10 minutes, then a good samaritan came and pulled me 
out. I offered him cash awkwardly, and he graciously refused. I was late to 
work, but John and Josh were later so it doesn't count. Josh brought donuts. 
Fresh donuts. I had forgotten donuts could be good, but these were subarashii. 
Did some more research on powershell stuff... Not really though... The emacs 
plugin does have a built in powershell dumb-terminal, so that's something. It's 
nigh trivial as a function, but it is something.
You know what's not something? Isekai.
Ooh, a tangent. Narnia the Magician's Nephew is an isekai, of the old kind 
where our guy wants to get back. I was just considering what I would do/think 
if I happened to get isekai'd, and what regrets I would carry or anything. 
Would I bring the Notch Apple back to my own dying mother? Would I attempt to 
contact my nakama to explain the event? Would I jump through hoops in that 
world to improve our own? Or even myself?
I don't know. I suspect if do the minimum necessary, and die like Subaru. 
Pointlessly, idiotically, dishonestly. And if I had to keep forward, I would 
lean on whatever the "twist" ends up being, till it failed me too. I would 
settle down and try for a white collar occupation that relies on my modern 
knowledge. And seek out all the infotainment there is in that world. If there 
would even be such a thing.
Other tangent: Would I be able to move our stories to this hypothetical isekai? 
The great epics of each generation: I suspect Homer would be a trivial port; 
Star Wars would fit just fine, Don Quixote is likewise omni-temporal. But these 
are plot-beated stories. What of mystery character technology drama? What of 
attack on Titan? What of (I could not think of another story of the same 
calibre).? So much is untranslatable in relation to the current and most 
fitting presentation. If I lose any, I lose it all. And if I lose it all, slip 
and fall, would you laugh at me.!?

* 2022-03-25 10:20 pm
Almost figured out printing in powershell. Or rather, I can get spacing or 
fonts but not yet both. A work in progress, but progress is being made at least.
Gave up on the whole server-and-hotspot thing for ThinkPad. Reset the router, 
it's doing its thing and routing the ports for ssh and https. Hopefully the 
dynu redirect will keep functioning. Hopefully...
Also. Got some good progress switching from vim wiki to orgmode. Now I've just 
gotta write an amateur sed script to convert all the formatting. Or just do it 
manually. Or just not. Plus the  system-crafter guy has a guide on getting it 
all set up so that's good.
Best thing: getting the site back up and working correctly. That is wonderful.

* 2022-03-26 10:34 pm
Watching Ascendence of a Bookworm. Exactly what I wanted in anime. Absolutely 
subarashii.
Also. Did some minor tweaking to emacs; I may just have to find another color 
scheme that actually works instead of my own hacked up nightmare...
Best thing: trying out doom emacs again and reading their docs. Gives a better 
perspective of what's out there to optimize.
Still not using their theme though.

* 2022-03-27 9:16 pm
Best thing: set up windows on the old dextop and simplified the Message script.

* 2022-03-28 7:48 pm
Best thing: simplifying the face definitions of my emacs colorscheme and 
working with the comment-delimiter stuff.
There's still more to do. I want to get all of Doom's org formatting in my 
fonts, and get the heading/ document structure figured out better. Or at least 
better fonts and colors.

* 2022-03-29 9:35 pm
Best thing: gui for ffcut script. Also super happy with my latest tweak to 
emacs: adding a better color to the variable-name face, which is also 
org-heading-2 for some reason. Previously it was very similar to my text face's 
off-yellow, which was not good. Now it's gray and thin. Maybe I should make it 
italic or underlined? Nah, that's too much. I want to keep this simple.
Man, all these dependencies take time to install and that's not good. Gotta 
eliminate a few. Once the colorscheme is done (ish) I can get rid of autothemer 
and just take its result. Also magit can go. I'm just not using it. Same with 
slime-- it's only good for automating nyxt, and nyxt does not work on any of my 
setups. Well that's an okay start to start with but there will need to be a lot 
more culling done later. The problem is, the defaults are just so bad. To make 
it bearable you need to disable all the gui bits, replace all the keybinds with 
a copy of vi, and hack ruthlessly at the cruft of ten thousand moons' 
optimizations for a bygone era.
Welp. I need to get up in the morning. Bye.

* 2022-03-30 9:07 pm
Best thing: rearranging the emacs color scheme. There's still a bunch of 
balance issues but I think it's getting better.

* 2022-03-31 11:33 pm
Best thing: deciding to walk to work tomorrow.
Also. Today I made the ffcut script download a static ffmpeg, since github 
doesn't let you upload files that big. I still want a progress bar, but for now 
this is fine.
For the Message script I need to chop up the text line. This can probably be 
done by counting a certain number of characters, finding the previous space, 
and converting it to a newline. And repeat until that is no longer possible 
obviously. I wish someone had already done that, but it'll be okay to do myself.

* 2022-04-01 10:17 pm
~How long, how long will I slide?~ (forever and ever amen)
~Suffer at the sight (I don't)~
~I don't believe it's better.~
Best thing: walking to work. Very relaxing. Also the paycheck. I've got an 
extra $300 plus another month of security.
Why do I struggle with human interactions? What do I gain from their confusion 
and pity? Well, I don't want to face them as an absolute. My absolute self is 
the hurricane, and I don't even care to look at it. Much less force others to.
Natsuki Subaru has "scary eyes". Shirogane Miyuki has "scary eyes". Ayanokoji 
Kiyotaka has dull eyes. I have weary eyes most of the time now. What does that 
mean? What eyes does Charles have? Can I ever look at him again, as anything?
I'm probably autistic. That's easy. But all the symptoms could also be from 
abuse. Was I abused? I remember nothing concrete. Only hating Dad for defying 
my little logic, and being glad to be stuck in Mom's nave box. In the box is 
peace and intermittent predictable isolation. She would give me free time based 
on work put in. Was it fair? Who knows anymore. But it was a good substitute. 
When dad was around, I was on edge. He made me come out and do things. Leave me 
the hell alone. Ive done my chore and a half, there is nothing to gain from 
sitting in the same room as you. You're just on your computer anyway. Maybe 
you'll make me listen to your sinful music. Maybe you'll rave about your stupid 
engine diagrams or amplifier circuits. Just leave me alone. Maybe you'll drag 
me on a hike to take the dog for a run. I'm in the middle of my daily cereal 
and comics. I'm not going. It'll be all soggy when I get back. I'll eat it now. 
At least give me 10 minutes to finish this part. Plus I have homework when I 
get back. I gotta do that now. This is my only reprieve today until I get to 
lie awake in bed for an hour. You are not taking this from me. Oh really. Well 
then. No more cereal and comics. Honey cancel the newspaper.
I'm in my room. Door is halfway open-- all the way open is wide and raw, closed 
or barely-ajar is hiding something. Building Legos quietly. Nothing else to do, 
but dad is here and he'll think of something if he remembers my existence. But 
I want this one part. I used a flashlight, it's right on the bottom of the 
drawer. If I sneak my hand in at just such an angle, my fingers should-- "I 
hear rustling. Mitch, get out here. What are you doing?" nothing. Like I 
should. I'm oppressed and you are bearing down on me like some	 kyojin I can't 
shingeki. I just want to live in peace. without you. Leave me alone. leave me 
alone. The fucking leave me the bloody damned hell a freaking lone. All I ever 
wanted to do was mind my own business and spend your money on toys and make up 
inane plots. Whenever you're around, I make no progress. When you leave, I have 
to compensate by making thrice as much sound, or getting on the forbidden 
computer, or going out to get candy to consume. I have to have it. You won't 
give it so I will take it. I will turn the whole house upside down if need be. 
I will find it all. Every computer, every candy stash. Every thing I can use 
and enjoy in secret, I will. You will tell me I was wrong, I will agree with my 
lips, but I will regret only being caught. I will carry out my punishments to 
the most barely sufficient degree, and move on to the next iteration. Until you 
give up. Until I am "worthy". Until I am "mature". "older". Oh stop. I'll never 
be good enough for you. You gave me my own computer to shut me up. You took it 
away because I gave you an excuse. It was all so pathetic from all of us.
Is that abuse? Yet my father says he is not abusive. And my father is an 
honorable man.
I have some choice words about Mom's role in all of this. Specifically, that 
she and her nearsighted good intentions created every stressful situation in my 
childhood. But that is for not-now.

* 2022-04-02 10:05 pm
Yay. Hooray. Here's another bad take.
Realist Hero is a good show. It's lacking in filler and full of 10 billion iq 
plays. The reference implementation of the intellectual's isekai power fantasy 
harem. I love it. It's reasonable and inspiring and hot. The plot has no 
obvious gaping holes, and if it did they would be explained anyway. I will 
eagerly await the next installment. This is still pretty early and they haven't 
even finished introducing characters, it seems. Lots of good potential there. 
Also. The romance. Can it even be called romance? Is romance a valid and 
iterable concept? Whatever. This particular isekai has legal polygamy, so yeah. 
Our boy the Realist Hero king is going to keep collecting waifus, that much is 
for certain. I love to see him succeed, but I'm slightly disappointed. Waifus 
#4 merchant princess brown edition was set up to be this puppeteering shadow 
alt-tagonist. She's a good character in her own right and had mentioned having 
her own agenda. And yet, her grand ploy is just to marry protag-kun and annex 
her lands to him. Okay other topic on the same show. Strangely, protag-kun 
despite actually being married to his obvious love interests, has not sexed 
them yet. Is it to keep his energy up because the act is draining? Is he afraid 
of getting too close or something? Is he worried about his public image? Or is 
he consciously aware of and seeking to preserve that isekai stereotype of the 
perpetually celibate harem? I mean, mad respect and restraint. Or maybe he's 
like me and has a terrible relationship with his sexuality and doesn't trust 
his stamina or body image with anyone else. Nah. He's probably just reasonably 
modest and a little shy and very preoccupied.
Best thing of today: working out putting a title on the site without it showing 
as a visual heading. That was good.
I'm tired. I'm depressed. I haven't met with any friends in about a month at 
least. Not since that retreat I ducked out of. I need new friends, but it's not 
that quick and easy...
At least I'm not on reddit. That has helped tremendously.

* 2022-04-03 9:30 pm
This document is huge. It's going to take a while to open every day unless I do 
something about it. Which I might. I sort of was planning to upload it to the 
website anyway.
A couple best things today:
- finally fixed line indentation on the Message script. Now I just need a basic 
email function and it will have surpassed John's.
- merged the self-hosted site with the github version. Now I can edit stuff any 
way whatsoever and it will appear on the github version instantly ish, and my 
own when I manually rebuild it.
Yes. It was probably a good day. My ears are lightly ringing, and I'm not sure 
how to feel about that. I only notice it when nothing is happening and I seek 
it out. But right now it's here and it won't go away.
I saw an article over a month ago, maybe less, about a Japanese kid who 
crunched the numbers of how hard various hiragana were to write. He assigned 
point values to straight and curved lines, then added them together for each 
letter. This is a thumbs up from me. It's something that's always been in the 
back of my mind, especially about Asian writing systems with lots of complex 
characters. But. The author of the article said that he was in awe in part 
because when he were that age, he would have said that the hardest letter to 
write was B because he didn't like broccoli. And there's just something so 
pathetic about that. This author was doomed from the start, and his attempt to 
endear himself just exemplifies his own idiocy. He never knew logic. It was as 
a third language to him, something that could be admired and pantonmimed, but 
never understood, never natively spoken. So he calls the kid /subarashii/ and 
himself a baka. He is aware of this, but not the implications. There is a 
sadness to it. Like Chris Chan. Like he is aware that he is a fool, and his 
work is worth nothing, and this pains him. Yet he cannot do anything about it 
nor reflect. For he is a fool and his work is worth nothing.
I bought a couple of pizzas today. I wonder: if I cut a slice off the frozen 
pizza and cook it on its own, does that work? Will it come out okay? Only time 
will tell. I'll finish the last of the first pizza tomorrow. Then can come the 
experiments...

* 2022-04-05 7:26 pm
I missed yesterday. I missed yesterday? Hmm. Best thing of yesterday: Jon 
telling me that he can hear minds. I basically believe it, too.
Best thing of today: starting to rewrite conan-dl in powershell this morning. 
It was all downhill from there though.
So. I think I have to start doing something else. In addition to the current 
stuff. I'm wasting a lot of time right now as it is. The intention is to 
gradually crank the sleep time earlier and earlier, to reclaim the morning 
pre-work. That way I can do more things on that first burst of energy, be 
depressed for work which is fine because Jon is depressed already so he might 
not notice, and might even be nicer to me. Then I go home and crash. And then 
wake up around 8 or 9 for a couple hours to eat or watch YT or whatever and 
sleep from 11 to 5. That's a very rough guesstimate and there's something wrong 
with it.
The problem with this is that it's light out and I have luxurious windows. 
Let's see. I can close the door, and put a thingy over the window in here. That 
could work. Let's try it. If I'm to train myself to wake up before the alarm, 
it must not be light-related.
I hereby wish my immediate future self luck!

* 2022-04-06 8:50 pm
Well that didn't work. At all? Not really. Not very much.
Best thing of today: idk it was awful. I've felt like that every day lately. 
Maybe, I need to make a change. Definitely, rather. Best thing for real today: 
starting this anime. It's got a stupid long poorly translated title: something 
like "isekai'd with my fellow old man friend who is now an impossibly beautiful 
girl". It's popcorn but doesn't get stuck in the teeth. So chips but not 
corrosively salty. So perfect basically.
I haven't finished it so there's not much to say. Lead guys are both relatable, 
lead girl is hot/cute (how far have I sunk that I can say that), visual 
exaggerations are on point if overly frequent. But again I'm only 2 episodes in 
so can't say.
You know what I'm way further into? Re:zero. I've caught up with the real 
translations and am now left with proofread machine-translations. But the 
machine is excellent at its job. The quality is indistinguishable. So. Subaru 
is sort of a weird case of male. Not worthy of being Alpha, not independent 
enough to be a Sigma, but will not submit to anyone. He meets the sigma emperor 
of Vollachia, goes through hell with him, and then clashes and distrusts him. 
And flares up at the guy constantly. Like, if I were in Subaru's place I would 
immediately swear fealty to the guy. I would also have kissed up to Julius in 
season 1 though, so that changes the timeline quite a bit already.
Did Subaru watch steins;gate? He mentions world lines a few times. Is that 
sekaisen, or another compound term? Huh. Oh well.
I've had a headache all afternoon ish. Why. I don't understand. Stop.
My tongue feels too big for my mouth. My eyes itch when I cry. My nose only 
works halfway and it switches without warning. My penis leaks droplets and 
leaves a stain on my pants. My ears feel clogged but I can hear everything. All 
my major joints have fat-folded skin behind them that looks like something out 
of snk with no magic regeneration or Titan powers. Basically, my whole body 
already feels like it's falling apart slowly. I can't imagine being John or 
Gene's age. To be in constant pain, to abandon an extremity and watch it rot 
and fall away, to lose sight and memory and adaptability. To see all the 
current days run together, to be unable to experience without comparing to your 
youth, to yell on the phone and misuse technology that should be simple. You 
should be smart enough to understand it. You're a smart person. How can you not 
comprehend one more thing? But that is the curse of age. You become like 
Chris-Chan or that reporter. You can see that you have become a pathetic 
existence, and even see how. But you are pathetic, so it brings you only 
fruitless pain, so you stay in your ever-shrinking box, to reign over your 
melting domain for as long as you have left.
I cannot stand that. I wouldn't want to be in that sort of world that I can see 
my link with crumbling. Build me a little padded static world I can live out my 
days in, with no challenges. Then I shall be content. Actually, do it now and I 
would be even more content.

* 2022-04-07 8:56 pm
Another day. Ate too much ice cream and now I won't be able to sleep for a 
while.
Mom is stupid. She doesn't read my texts. She keeps asking me to come over and 
fix the lamp. She's moving out in 2 days! She doesn't need that lamp! I will 
not interact with her anymore. This is a garbage situation and the least I can 
do is stay out of it.
I also just want an excuse to not see her. She pains me and has for years. I 
wish she'd go. Go to Spokane or something, stop ruining my life up here. Then I 
can go back to church and give her downfall as the backstory of my conversion. 
What a convenient and subarashii tale. Only my confidanti would know the truth, 
that the church is mostly aesthetic to me and I left because I couldn't stand 
her. Ah yes. All that will unfold in due time.
Originally the plan was for her to die, but this is a lot cleaner and actually 
under way already. Kamisama, I really ought to be thanking you.
Of course, there's a whole lot of other things I want to be before this is all 
over...
Once I get a little more in shape, I can start researching hormone 
manipulation. I want to not have the urge to masturbate. That's it. Mostly. 
Also it would be kind of fun to have breasts, and convenient not to have to 
shave... There's probably some huge downside to it I haven't heard of because 
of the propaganda.
Of the 2 sexes, I'd much rather be male. There's no inherent pain, your base 
strength stat is at least functional, and you can be largely level-headed at 
any given time. I would never choose to be born a woman. Periods alone sounds 
like hell. And it's all the time. Well, a solid quarter of the time. Plus women 
are a more toxic community and male society doesn't respect women enough.
But if I got to pick the best traits from each sex, I would prefer a female 
phisyque with male plumbing. Roughly. Aach. I'm being lazy. I just don't want 
to shave. I don't want to shave, I don't want random boners, I want female 
friends. I guess I'm no better than Chris Chan in that regard. But. I would 
never identify as a woman. I'd sooner be gay. Wouldn't mind being gay, in fact. 
If it was a guy I could really share a future with.
Because really, that's what I want. I just want a companion who I can talk with 
who will support me and be there and that I can learn more about. I want 
someone to love, somebody to love me. A hug. Please God I need a hug. Anybody. 
Hug me. Guess I'm no better than Sockness in that regard...
Oh right. Best thing of today: abstracting parts of the scripts into a separate 
file. And next time I may do some sort of exe compilation. Hopefully that will 
hide the host window better than my current solution...
Ooh. An idea to work on to maybe help. A goal for tomorrow.
Goal for tomorrow: make ffcut smooth. Progress bar at least.
Satte. Oyasumi.

* 2022-04-08 10:45 am
Today is Mary Alice's birthday. For all the nil that's worth. Random pointless 
aside.
Anyway.
New discovery: in Emacs you can type C-\ and it will bring up a list of input 
methods. This is independent of the OS and translates the keystrokes the same 
way as emacs key chords. It has Japanese. We can type raw phonetic Japanese and 
it will look real and readable.
Now the problem is katakana and Kanji. No idea what to do about those. Is there 
already something built in? Probably. Yay. Happy happy fun times. Just wanted 
to add this to the record before I forget...

* 2022-04-08 4:39 pm
Another emacs thing:
global-whitespace-mode for tab visualization.

* 2022-04-08 10:47 pm
Both above emacs things are now incorporated into my configuration. Hooray.
Best thing of today: getting Japanese input and whitespace visualization on 
emacs. It's like in the movies, literally. You just type and it converts the 
characters.
Now what we need is to merge quail (the emacs foreign input system) into 
ivy/counsel...
I'm tired. Good night.

* 2022-04-09 11:14 pm
Best thing of today: optimizing emacs startup time. It was getting up to a 
second there until today. Now it's about half. I'd prefer even less, but this 
is fine for now.

* 2022-04-10 5:58 pm
Finally got space bar prefixes on emacs figured out. Haven't implemented them 
yet but they're figured out at least. Using general.el for all keybindings 
seems to be working out.
I successfully shunted away both parents' appointments with me yesterday. Mom 
by disappointing her sorry self, and dad by not needing his help.
The apartment has been cold today. Figures, since I have the heat cranked way 
down. Me plus the sun are probably sufficient to maintain a good enough 
temperature for the system as currently configured. My toes are cold, but the 
rest of me is fine. It might be a good thing, since I have to burn more energy 
to just exist. But then again, when it's warm I sweat too much anyway and 
that's tiring and uncomfortable. Plus when it's hot the bedbugs come out. When 
it's cold like this we can pretty well pretend they don't exist, since they 
deactivate in the cold. Or something.

* 2022-04-10 9:01 pm
Best thing of today: tackling emacs prefix keys. Soon I will have everything on 
spacebar and need no modifier keys. No control, no meta. And hopefully in a 
remember-able way.
It's a good day. I have been saved. I am not Chris Chan. Thus I shall endure.

* 2022-04-11 9:21 pm
Best thing of today: adding treemacs and minimap to emacs. The minimap is kind 
of broken, but it's fine for now. I think the implementation is rather fraught, 
inherently, but surprisingly there are only 2 and the other one is worse. 
Treemacs is also fine. The least janky out of the options in one random list. 
Also has git integration which is neat I guess.
Things go by in a whirl. It's already April 11th. In a month the others will 
get out of school and have summer free time all day. And I won't. I'll be stuck 
in the office. Making bank. And maybe I'll save a thousand dollars, and maybe 
I'll find a shorter job, and maybe I'll get some friends somehow, and hang out 
all day long.
Kind of doubt that last one. But hey, there's always a chance.
Most of my friends so far have been circumstantial. You meet them, try being 
enemies, get tired of that, and confide in each other and get up to 
lesser-good. And then your circumstances stop aligning, and nothing. It's like 
a switch. Was it my idea to break contact? Or theirs? Both, and neither. We 
just couldn't bring ourselves to go that far out of our way. The bond we shared 
was wide but shallow. There is always of course the repulsion factor. Like 
malformed magnets that push each other apart unless you get them really close, 
then they stick tightly. When you pull them apart, they'll never reconnect on 
their own.
Or maybe I'm just antisocial, or maybe I'm too emotional, or maybe I'm just 
afraid of what they'd say.
I'm blaming society. It separates us. I'm a year ahead, thus I as an adult am 
on a completely different plane of existence. It's the same reason I didn't go 
on that retreat. I'm not ready to be a leader. To the extent that I've ever 
been a student/subordinate/etc, I still am. I feel exactly the same and I 
relate most to that status and those fellows. To be in a managerial position 
for me is to have lost. I'd do it if I had to, but I always think of myself as 
the lowest rung. The top of the lowest rung. It's exactly like that at the 
office. That is part of my current contentment. I am the lowest position, 
second assistant and discovery enumerator, but I am the best one they've ever 
had. All of my obligations are:
- confined to the office,
- either
   1. Consistent and scripted; or
   2. Immediate and simple.
This is ideal. No homework, very few curve-balls. But plenty of busy work that 
is necessary and on a soft time deadline.
What does this account say about me? What does it say about you for reading it? 
That is something only we together can answer. May you by reading this 
assimilate my mind, and judge for yourself truly.

* 2022-04-12 9:35 pm
I just set up the file syncer, so it might or might not have sync'd up. Let's 
check.

* 2022-04-12 10:56 pm
Best thing: notes sync. I don't even care if it actually worked. Today was 
vicariously stressful and I did nothing else of note.

* 2022-04-13 6:24 pm
Bad day. But got bone-conduction headphones so that's nice.

* 2022-04-13 6:36 pm
Testing. Did the sync work? Did it?
Apparently so.
I just went in and fixed all the date headings, and a few of the song lyric 
bits...

* 2022-04-13 7:32 pm
And now maybe the line breaks will work. Maybe. Pray to the capricious regex 
gods...
No. It didn't. Whatever. Not like I want anyone to read this...
Hmm.

* 2022-04-13 9:56 pm
Best thing: working out the note syncing. The only other good thing that 
happened was hanging foil on the window. Maybe I'll be able to sleep earlier 
now.

* 2022-04-14 9:26 pm
Best thing of today: waking up early and taking a shower.
Okay, hmm. Ani-cli broke again. Might have to switch to anime-dl if that's a 
thing. Which it definitely is.

* 2022-04-14 10:07 pm
Well, I'm trying again with converting ani-cli to powershell. I actually 
nanaged to appease the linter, so that's at least a start. However the output 
looks like this:
#+begin_src
False
False
$*
False
$*
#+end_src
Clearly, something is wrong. I blame the syntax differences.
Powershell is wonderful. Absolutely crazy. Like sh but doesn't get in your way.

* 2022-04-16 7:39 pm
I missed yesterday, apparently. Didn't notice at all. Best thing of yesterday: 
porting John's email button in the script from visual basic to powershell. Even 
if it's still mysteriously broken. Just having a reference is a big help.
Did I lose time? I legit can't remember much from yesterday. I didn't wake up 
early, the alarm was My War (from attack on Titan), at work I did the email 
thing and a bunch of discovery, and I must have had cheeto Mac in the evening 
because the tupperware was oily and orange. Oh yeah. We had subway for lunch 
and Josh was late picking it up.
Best thing of today: fixing the READMEs for my dotfiles. Also the tangent that 
that led me on led to using zplug to manage more things was pretty useful. I 
want to do more with that sooner or later. But for now the next thing is to 
auto-tangle all those org files. Ideally both on save and when deploying a new 
system. There's gotta be a way to do that, right? Well I'll find it. And do all 
the other things as well. If I could manage everything with zplug that would be 
supremely convenient...
What has this file become? All I do is gush about my pseudo-programming 
escapades. Where are the hot takes? The rants? The reviews? They're all in my 
head, and I'm not in the space to let them out lately. I'm pretty full right 
now. Tomorrow I may or may not go to Dad's for Easter. May as well, except for 
the whole gas thing. Well, I've got some 20s in the car, 30ish in my pocket, 
and 10 extra in savings. That's an amount. I can drive to Eagle River Carrs, 
deposit/transfer at the atm, and get gas there too.
Or I could just not. And chill here, and watch anime and program all day, and 
snack on the last of my chips and salsa, then cook a spoonful of over-seasoned 
rice. I really have to find a better use for that rice. Ooh. Frozen 
blueberries, milk, cinnamon, ginger. Boil the rice, simmer in blueberries, stir 
in ginger, dust with cinnamon. I feel less bloated just thinking about it. But 
still bloated.
The car is going to be trouble. I need to get my studs off. Ooh. I'll do that 
in Palmer. There's a place by dad's. And I can walk. I need to get some 
exercise. Any at all.

* 2022-04-17 10:06 pm
Why, oh why. Did I go. To dad's. I wasted like 5 hours and a good amount of 
gas, and for what? Well, I at least got the tires. Need to change those very 
soon... Like a week ago...
Best thing of today: laying here now. Tired but resigned. I need nothing else.

* 2022-04-18 9:32 pm
~I need something else, to get me through this~ stupid song. Darn stupid 
innuendic songs. I can't stand it. I've stood it for a while now, what happened 
was nothing.
Father Arthur called me today. I was real with him for once. I told him that my 
piety was aesthetic. I told him I was staying away from mass because I didn't 
want to run into mom. He accepted it all and told me that I can use my powers 
for good or for evil. Hmm. Yeah, I bet. I told him I didn't want to go to 
college because homework and stress. He said to wait and when I get to it it 
won't be like I remember. I think he may have been a bit overwhelmed by how 
much I shared. Oh well. That is one affliction with which I am cursed.
Best thing of today: sending email works. In powershell. Now I just have to 
give feedback on it.

* 2022-04-19 8:12 am
Jon out today. Guess I'll just sit here and do nothing. Nah, I'll do something 
at least. May as well.
Well, I restarted the ordeal of rewriting ani-cli in powershell. Copying the 
i/o of each function, but writing them idiomatically to powershell. It'll be 
good this time. I don't have complete certainty, but I have faith in myself.
Doom. Depression. Desperation. ~so far away, we wait for the day / for the 
light's also wasted and gone / we feel the pain of a lifetime lost in a 
thousand days /through the fire and the flames we carry on~
I am a kid. A child. I believe in children. Is that all that means to me? I am 
a grown up. Adulting all over the place. I got a life and a job and a place to 
live. And yet. I am not "an adult like them". To grow up is to kill your old 
self. To want to do things that are stupid and that you shouldn't want to do, 
that society demands. To enslave yourself to the system. "I have to do my 
taxes" so you want to. "no, but I have to" so you do them willingly despite not 
"wanting" to do them. Truly pathetic. Just admit that you like it. If you 
didn't, you would resist with all your everything, and make up for it later. To 
submit is to submit willingly. And to be willing is to want. When this all 
shakes out, you want this.
What do I want? ~I want to shine down, on the hearts of man, I want to take it 
from the back of my broken hands~. Well, sort of.

* 2022-04-19 9:50 pm
My ears are ringing. They start whenever I don't have anything to listen to or 
concentrate on. If I stop listening to it, it goes away until the next time. I 
pop my ears and pressurize my sinuses. But nope. It endures.
Worst thing of today: all of work.
Best thing of today: working with powershell string manipulation for the 
ani-cli rewrite. Most of the logic is simple to port, but I'm not sure how to 
handle passing multi-line stdin to a While loop. I guess just use For and pipe 
into .Add($_) if they'll let me.

* 2022-04-20
My headache is splitting. I cannot think, I cannot live. I'm just sitting and 
breathing and listening to the ringing of my ears.
Best thing of today: not getting pulled over this morning. There was a cop 
right there and he didn't even look my way.

* 2022-04-21 8:29 pm
My brain no longer trembles, but the throat is ravaged and my shoulders want to 
fall off. Weird. Unpleasant, but not quite as bad as yesterday. Nay, so much 
better than yesterday. Last night I was up the whole time having nightmares 
about GiBi and powershell recursion and entitled criminals. And having to pee, 
of course.
Well, I went to the store and got some chicken soup and a pot pie. I ate the 
pot pie. Burnt my tongue a little bit but could still mostly taste. Also, whole 
milk is the best. Very underrated.
I watched Dress Up Darling today. Wholesome and original, but it's total 
waifu-bait ecchi garbage. Makes up for a cringe and inevitable plot with sexy 
animation. That's my brief rambling review. It's probably wrong because 
everyone on YouTube says it's fantastic. Well, whatever. At least I'm not 
blindly following somebody's takes on it like I do for most things.
Best thing of today: walking around Fred Meyer. I almost felt normal.

2022-04-22 10:34 pm
The ache is pretty much gone from my shoulders. But my throat is scabbing 
itself over a lot. Does it not know how to heal? Nah, it shall heal in time.
Best thing of today: getting a good version of Emacs for macos installed. The 
built-in webkit browser almost doesn't not work. Only problem, I use emacs as a 
transient process and not as a daemon or root window. Thus having to open and 
close the browser along with the editor all the time. Not ideal.

* 2022-04-23 3:40 pm
Current at random tire shop #1 waiting on my car. The one Jon gave me didn't 
answer.

* 2022-04-23 8:51 pm
Best thing of today: walking around after dropping off the car. Didn't get 
anywhere but at least I burned energy.

* 2022-04-24 8:33 pm
Just watched (finished) Serial Experiments Lain...
** Quick rant/review: Serial Experiments Lain
So, um, it's like, if, uh, The Matrix were depressed and suicidal and, uh, umm 
like deep and stuff, kinda reminded me of Steins gate for no reason, and uh, 
like, computers are crazy yo, and like what is this setting? So yeah. Cathartic 
plot collapse out of 10; must watch.
** best thing of today:
 getting blazers out of car. Needed to happen for months now.

* 2022-04-25 8:42 pm
Best thing of today: shower in the morning. All downhill from there, now my 
headache is back. Night.

* 2022-04-26 10:05 pm
Best thing of today: installing the new Ubuntu. It's broken so I'll have to go 
back to fedora, though. That can wait till tomorrow.

* 2022-04-27 10:08 am
At work right now, might randomly trail off.
I used to be good with people. I used to not get flight or fight reactions when 
going up against a crowd.

* 2022-04-27 9:56 pm
Best thing of today: not finishing lunch. I feel like I've gotten less hungry 
which is a step forward.
